Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-06, with the labels that each got.

#925 build(all): use es2019 target to support on Node12
  .github/workflows/pr_lint_and_test.yml
  .github/workflows/run-e2e-tests.yml
  examples/cdk/tsconfig.json
  examples/lambda-functions/tsconfig.json
  examples/sam/src/tsconfig.json
  examples/sam/tsconfig.json
  package-lock.json
  package.json
  packages/commons/tsconfig-dev.json
  packages/commons/tsconfig.json
  packages/logger/src/Logger.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/logger/tsconfig-dev.json
  packages/logger/tsconfig.es.json
  packages/logger/tsconfig.json
  packages/metrics/src/Metrics.ts
  packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
  packages/metrics/tests/e2e/basicFeatures.manual.test.ts
  packages/metrics/tsconfig.es.json
  packages/metrics/tsconfig.json
  packages/tracer/src/Tracer.ts
  packages/tracer/src/middleware/middy.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
  packages/tracer/tests/unit/Tracer.test.ts
  packages/tracer/tsconfig.es.json
  packages/tracer/tsconfig.json
Labels: fix

#903 chore(examples): cleanup old examples
  README.md
  docs/index.md
  packages/commons/README.md
  packages/logger/README.md
  packages/logger/examples/additional-keys.ts
  packages/logger/examples/child-logger.ts
  packages/logger/examples/constructor-options.ts
  packages/logger/examples/custom-log-formatter.ts
  packages/logger/examples/custom-logger-options.ts
  packages/logger/examples/ephemeral-attributes.ts
  packages/logger/examples/errors.ts
  packages/logger/examples/hello-world.ts
  packages/logger/examples/inject-context-decorator.ts
  packages/logger/examples/inject-context-middleware.ts
  packages/logger/examples/inject-context.ts
  packages/logger/examples/persistent-attributes.ts
  packages/logger/examples/sample-rate.ts
  packages/logger/examples/utils/config/CustomConfigService.ts
  packages/logger/examples/utils/formatters/CustomLogFormatter.ts
  packages/logger/examples/utils/formatters/MyCompanyLogFormatter.ts
  packages/logger/examples/utils/lambda/LambdaInterface.ts
  packages/logger/examples/utils/lambda/index.ts
  packages/logger/package.json
  packages/logger/tests/unit/Logger.test.ts
  packages/metrics/README.md
  packages/metrics/examples/cold-start.ts
  packages/metrics/examples/constructor-options.ts
  packages/metrics/examples/decorator/cold-start.ts
  packages/metrics/examples/decorator/constructor-options.ts
  packages/metrics/examples/decorator/default-dimensions-constructor.ts
  packages/metrics/examples/decorator/default-dimensions.ts
  packages/metrics/examples/decorator/dimensions.ts
  packages/metrics/examples/decorator/empty-metrics.ts
  packages/metrics/examples/decorator/hello-world.ts
  packages/metrics/examples/decorator/manual-flushing.ts
  packages/metrics/examples/decorator/manual-metrics-print.ts
  packages/metrics/examples/decorator/single-metric.ts
  packages/metrics/examples/default-dimensions-constructor.ts
  packages/metrics/examples/default-dimensions.ts
  packages/metrics/examples/dimensions.ts
  packages/metrics/examples/empty-metrics.ts
  packages/metrics/examples/hello-world.ts
  packages/metrics/examples/manual-flushing.ts
  packages/metrics/examples/manual-metrics-print.ts
  packages/metrics/examples/single-metric.ts
  packages/metrics/examples/utils/lambda/LambdaInterface.ts
  packages/metrics/examples/utils/lambda/index.ts
  packages/metrics/package.json
  packages/tracer/README.md
Labels: internal

#945 build(deps): bump broken Depdendabot deps
  package-lock.json
  packages/logger/package.json
  packages/tracer/package.json
Labels: dependencies

#878 feat (build): Add package size check in PR workflow
  .github/workflows/pr_lint_and_test.yml
  examples/cdk/package.json
  examples/sam/package.json
  package-bundler.sh
  package.json
  packages/commons/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/tracer/package.json
Labels: internal

#902 feat(logger): add clear state functionality
  docs/core/logger.md
  package-lock.json
  packages/commons/tests/utils/e2eUtils.ts
  packages/logger/src/Logger.ts
  packages/logger/src/helpers.ts
  packages/logger/src/middleware/middy.ts
  packages/logger/src/types/Logger.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/helpers.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
Labels: feature

#992 chore: disable dependabot for dependencies upgrades
  .github/dependabot.yml
Labels: dependencies, internal

#1005 chore: updated rc release flow
  .github/workflows/on-release-prod.yml
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/sam/package-lock.json
  examples/sam/package.json
Labels: internal

#1009 docs: update docs to reflect RC status
  README.md
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/index.md
  packages/commons/README.md
  packages/commons/package.json
  packages/logger/README.md
  packages/logger/package.json
  packages/metrics/README.md
  packages/metrics/package.json
  packages/tracer/README.md
  packages/tracer/package.json
Labels: documentation
