Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-11, with the labels that each got.

#1125 chore(all): removed unused npm scripts + moved linting in PR checks
  .devcontainer/devcontainer.json
  .github/workflows/pr-run-linting-check-and-unit-tests.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .gitpod.yml
  .husky/pre-commit
  .husky/pre-push
  CONTRIBUTING.md
  examples/cdk/.eslintrc.js
  examples/cdk/.gitignore
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/cdk/tsconfig.es.json
  examples/sam/.eslintrc.js
  examples/sam/package-lock.json
  examples/sam/package.json
  examples/sam/tsconfig.es.json
  layer-publisher/.eslintrc.js
  layer-publisher/.gitignore
  layer-publisher/package-lock.json
  layer-publisher/package.json
  layer-publisher/tsconfig.es.json
  package.json
  packages/commons/package.json
  packages/idempotency/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/tracer/package.json
Labels: internal

#1144 docs(all): update & revise docstring examples
  docs/core/tracer.md
  packages/logger/src/Logger.ts
  packages/logger/src/middleware/middy.ts
  packages/metrics/src/Metrics.ts
  packages/metrics/src/middleware/middy.ts
  packages/tracer/src/Tracer.ts
  packages/tracer/src/middleware/middy.ts
Labels: documentation

#1146 fix(metrics): store service name in defaultDimensions to avoid clearing it
  packages/metrics/src/Metrics.ts
  packages/metrics/tests/unit/middleware/middy.test.ts
Labels: bug, utility:metrics

#1150 chore(docs): update layer version to 5
  docs/index.md
Labels: internal

#1155 chore: add codespaces badge
  .devcontainer/Dockerfile
  CONTRIBUTING.md
Labels: internal

#1152 docs: clarify nodejs16 requirement + fix command
  CONTRIBUTING.md
  package.json
Labels: documentation

#1110 feat(idempotency): Add persistence layer and DynamoDB implementation
  package-lock.json
  package.json
  packages/idempotency/jest.config.js
  packages/idempotency/package-lock.json
  packages/idempotency/package.json
  packages/idempotency/src/EnvironmentVariablesService.ts
  packages/idempotency/src/Exceptions.ts
  packages/idempotency/src/persistence/DynamoDbPersistenceLayer.ts
  packages/idempotency/src/persistence/IdempotencyRecord.ts
  packages/idempotency/src/persistence/PersistenceLayer.ts
  packages/idempotency/src/persistence/PersistenceLayerInterface.ts
  packages/idempotency/src/persistence/index.ts
  packages/idempotency/src/types/DynamoPersistenceConstructorOptions.ts
  packages/idempotency/src/types/IdempotencyRecordOptions.ts
  packages/idempotency/src/types/index.ts
  packages/idempotency/tests/helpers/populateEnvironmentVariables.ts
  packages/idempotency/tests/unit/EnvironmentVariableService.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/IdempotencyRecord.test.ts
  packages/idempotency/tests/unit/persistence/PersistenceLayer.test.ts
Labels: feature

#1162 chore(internal): remove unused test folder from project's root
  packages/commons/src/samples/resources/contexts/hello-world.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/metrics/tests/unit/Metrics.test.ts
  packages/metrics/tests/unit/middleware/middy.test.ts
  packages/tracer/tests/unit/Tracer.test.ts
  tests/resources/contexts/hello-world.ts
  tests/resources/events/aws/apigateway-authorizer.json
  tests/resources/events/aws/apigateway-aws-proxy.json
  tests/resources/events/aws/appsync-resolver.json
  tests/resources/events/aws/batch-get-job.json
  tests/resources/events/aws/batch-submit-job.json
  tests/resources/events/aws/cloudformation-create-request.json
  tests/resources/events/aws/cloudfront-ab-test.json
  tests/resources/events/aws/cloudfront-access-request-in-response.json
  tests/resources/events/aws/cloudfront-http-direct.json
  tests/resources/events/aws/cloudfront-modify-querystring.json
  tests/resources/events/aws/cloudfront-modify-response-header.json
  tests/resources/events/aws/cloudfront-multiple-remote-calls-aggregate-response.json
  tests/resources/events/aws/cloudfront-normalize-querystring-to-improve-cache-hit.json
  tests/resources/events/aws/cloudfront-redirect-on-viewer-country.json
  tests/resources/events/aws/cloudfront-redirect-unauthenticated-users.json
  tests/resources/events/aws/cloudfront-response-generation.json
  tests/resources/events/aws/cloudfront-serve-object-on-viewer-device.json
  tests/resources/events/aws/cloudfront-simple-remote-call.json
  tests/resources/events/aws/cloudwatch-logs.json
  tests/resources/events/aws/cloudwatch-scheduled-event.json
  tests/resources/events/aws/codecommit-repository.json
  tests/resources/events/aws/codepipeline-job.json
  tests/resources/events/aws/cognito-sync-trigger.json
  tests/resources/events/aws/config-oversized-item-change-notification.json
  tests/resources/events/aws/config-periodic-rule.json
  tests/resources/events/aws/confit-item-change-notification.json
  tests/resources/events/aws/connect-contact-flow-event.json
  tests/resources/events/aws/dynamodb-update-2.json
  tests/resources/events/aws/dynamodb-update.json
  tests/resources/events/aws/kinesis-analytics-compressed.json
  tests/resources/events/aws/kinesis-analytics-dynamodb.json
  tests/resources/events/aws/kinesis-analytics-kpl.json
  tests/resources/events/aws/kinesis-analytics.json
  tests/resources/events/aws/kinesis-apachelog.json
  tests/resources/events/aws/kinesis-cloudwatch-logs-processor.json
  tests/resources/events/aws/kinesis-get-records.json
  tests/resources/events/aws/kinesis-kinesis-firehose.json
  tests/resources/events/aws/kinesis-streams-source.json
  tests/resources/events/aws/kinesis-syslog.json
  tests/resources/events/aws/rekognition-s3-request.json
  tests/resources/events/aws/s3-delete.json
  tests/resources/events/aws/s3-put.json
  tests/resources/events/aws/sagemaker-ground-truth-annotation-consolidation.json
  tests/resources/events/aws/sagemaker-ground-truth-pre-human.json
  tests/resources/events/aws/ses-email-receiving.json
  tests/resources/events/aws/sns-notification.json
  tests/resources/events/aws/sqs-receive-message.json
  tests/resources/events/aws/stepfunctions-error.json
  tests/resources/events/custom/hello-world.json
Labels: internal

#1153 docs: update environment variable tables for utilities
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/index.md
  packages/commons/src/Utility.ts
  packages/commons/tests/unit/Utility.test.ts
  packages/logger/src/Logger.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/helpers.test.ts
  packages/metrics/src/Metrics.ts
  packages/metrics/tests/unit/Metrics.test.ts
  packages/tracer/src/Tracer.ts
  packages/tracer/tests/unit/Tracer.test.ts
Labels: area/documentation, size/L

#1165 feat(logger): disable logs while testing with jest --silent in dev env
  docs/core/logger.md
  packages/logger/src/Logger.ts
  packages/logger/src/config/ConfigServiceInterface.ts
  packages/logger/src/config/EnvironmentVariablesService.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/logger/tests/unit/helpers.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
Labels: area/logger, size/L, type/enhancement

#1167 docs: add maintainers and public roadmap
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_improvements.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign-issues.yml
  .github/release-drafter.yml
  .github/scripts/constants.js
  .github/scripts/label_pr_based_on_title.js
  .github/scripts/label_related_issue.js
  .github/scripts/post_release.js
  .github/stale.yml
  CONTRIBUTING.md
  MAINTAINERS.md
  README.md
  docs/requirements.txt
  docs/roadmap.md
  mkdocs.yml
  packages/commons/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/tracer/README.md
Labels: area/documentation, size/XL

#1168 feat(parameters): added `BaseProvider` class
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  package.json
  packages/parameters/jest.config.js
  packages/parameters/package.json
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/Exceptions.ts
  packages/parameters/src/ExpirableValue.ts
  packages/parameters/src/GetMultipleOptions.ts
  packages/parameters/src/GetOptions.ts
  packages/parameters/src/constants.ts
  packages/parameters/src/index.ts
  packages/parameters/src/types/BaseProvider.ts
  packages/parameters/src/types/index.ts
  packages/parameters/tests/helpers/populateEnvironmentVariables.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tsconfig-dev.json
  packages/parameters/tsconfig.es.json
  packages/parameters/tsconfig.json
Labels: area/parameters, size/XL, type/feature

#1181 chore(layer): reduce size by 3 by removing @types packages
  layer-publisher/src/powertools-typescript-layer.ts
Labels: type/internal, size/XS

#1178 fix(logger): merge child logger options correctly
  package-lock.json
  packages/logger/package.json
  packages/logger/src/Logger.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/helpers.test.ts
Labels: type/bug, area/logger, size/L

#1183 chore: add install step in docs workflow
  .github/workflows/reusable-publish-docs.yml
  packages/idempotency/package.json
  packages/parameters/package.json
Labels: type/internal, size/S

#1184 docs: update layer version to 6
  docs/index.md
Labels: size/M
