Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-12, with the labels that each got.

#1188 docs: added Node.js 12 deprecation banner to docs
  docs/overrides/main.html
Labels: area/documentation, size/XS

#1194 chore: remove httpbinorg request from integration tests
  packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
Labels: type/internal, size/M

#1180 docs: refresh SAM examples
  examples/lambda-functions/common/constants.ts
  examples/lambda-functions/common/dynamodb-client.ts
  examples/lambda-functions/common/powertools.ts
  examples/lambda-functions/get-all-items.ts
  examples/lambda-functions/get-by-id.ts
  examples/lambda-functions/put-item.ts
  examples/sam/.gitignore
  examples/sam/README.md
  examples/sam/package-lock.json
  examples/sam/package.json
  examples/sam/src
  examples/sam/src/get-all-items.ts
  examples/sam/src/get-by-id.ts
  examples/sam/src/put-item.ts
  examples/sam/src/tsconfig.json
  examples/sam/template.yaml
  examples/sam/tests/sam.test.ts
  examples/sam/tsconfig.json
Labels: area/documentation, size/XL

#1196 docs: update sam example to nodejs18
  examples/lambda-functions/tsconfig.json
  examples/sam/README.md
  examples/sam/package-lock.json
  examples/sam/package.json
  examples/sam/src
  examples/sam/src/common/constants.ts
  examples/sam/src/common/dynamodb-client.ts
  examples/sam/src/common/powertools.ts
  examples/sam/src/get-all-items.ts
  examples/sam/src/get-by-id.ts
  examples/sam/src/put-item.ts
  examples/sam/template.yaml
  examples/sam/tests/sam.test.ts
  examples/sam/tsconfig.es.json
  examples/sam/tsconfig.json
Labels: area/documentation, size/L

#1197 docs: update CDK example to nodejs18
  examples/cdk/README.md
  examples/cdk/functions/common/constants.ts
  examples/cdk/functions/common/dynamodb-client.ts
  examples/cdk/functions/common/powertools.ts
  examples/cdk/functions/get-all-items.ts
  examples/cdk/functions/get-by-id.ts
  examples/cdk/functions/put-item.ts
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/cdk/src/example-function.MyFunction.ts
  examples/cdk/src/example-function.MyFunctionWithDecorator.ts
  examples/cdk/src/example-function.MyFunctionWithMiddy.ts
  examples/cdk/src/example-function.Tracer.CaptureErrorDisabled.ts
  examples/cdk/src/example-function.Tracer.CaptureResponseDisabled.ts
  examples/cdk/src/example-function.Tracer.Decorator.ts
  examples/cdk/src/example-function.Tracer.Disabled.ts
  examples/cdk/src/example-function.Tracer.Manual.ts
  examples/cdk/src/example-function.Tracer.Middleware.ts
  examples/cdk/src/example-function.Tracer.PatchAWSSDKv2.ts
  examples/cdk/src/example-function.Tracer.PatchAWSSDKv3.ts
  examples/cdk/src/example-function.Tracer.PatchAllAWSSDK.ts
  examples/cdk/src/example-function.ts
  examples/cdk/src/example-stack.ts
  examples/cdk/tests/cdk-app.test.ts
  examples/cdk/tsconfig.es.json
  examples/cdk/tsconfig.json
  examples/sam/README.md
Labels: area/documentation, size/XXL

#1201 fix(logger): logger throws TypeError when log item has BigInt value
  package-lock.json
  packages/logger/package.json
  packages/logger/src/Logger.ts
  packages/logger/src/log/LogItem.ts
  packages/logger/tests/unit/Logger.test.ts
Labels: type/bug, size/L

#1205 refactor(parameters): BaseProvider support for Uint8Array
  package-lock.json
  packages/parameters/package.json
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/ExpirableValue.ts
  packages/parameters/src/types/BaseProvider.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
Labels: area/parameters, size/L, type/feature
