Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-10, with the labels that each got.

#1109 fix(tracer): captureMethod detects proper method name when used with external decorators
  packages/tracer/src/Tracer.ts
  packages/tracer/tests/unit/Tracer.test.ts
Labels: bug, utility:tracer

#1095 feat: publish lib as Lambda Layer
  .github/workflows/publish_layer.yaml
  CONTRIBUTING.md
  docs/index.md
  examples/cdk/.gitignore
  examples/cdk/README.md
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/cdk/src/example-function.ts
  examples/cdk/src/example-stack.ts
  examples/cdk/tests/cdk-app.test.ts
  examples/sam/README.md
  layer-publisher/cdk-lambda-powertools-python-layer@0.0.0.jsii.tgz
  layer-publisher/package-lock.json
  layer-publisher/package.json
  layer-publisher/src/layer-publisher-stack.ts
  layer-publisher/src/powertools-typescript-layer.ts
  layer-publisher/tests/unit/__snapshots__/layer-publisher.test.ts.snap
Labels: feature

#1112 chore(build): fix ts-node version for layer-publisher
  layer-publisher/package-lock.json
  layer-publisher/package.json
Labels: internal

#1113 doc(layer): bump layer version to 2 to match the one built for latest version (1.2.1)
  docs/index.md
  layer-publisher/src/powertools-typescript-layer.ts
  layer-publisher/tests/unit/__snapshots__/layer-publisher.test.ts.snap
Labels: documentation

#1092 feat(tracer): specify subsegment name when capturing class method
  docs/core/tracer.md
  packages/tracer/src/Tracer.ts
  packages/tracer/src/TracerInterface.ts
  packages/tracer/src/middleware/middy.ts
  packages/tracer/src/types/Tracer.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
  packages/tracer/tests/e2e/constants.ts
  packages/tracer/tests/unit/Tracer.test.ts
Labels: utility:tracer, feature, area/tracer

#1116 chore(layer): fix bundling and e2e tests by manually setting hash of asset
  layer-publisher/package-lock.json
  layer-publisher/package.json
  layer-publisher/src/powertools-typescript-layer.ts
  layer-publisher/tests/e2e/happy-case.test.lambda.ts
  layer-publisher/tests/unit/__snapshots__/layer-publisher.test.ts.snap
Labels: internal

#1119 fix(all): update version command to use lint-fix
  package.json
  packages/commons/package.json
  packages/idempotency/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/tracer/package.json
Labels: bug, internal

#1120 docs: update layer version in docs
  docs/index.md
Labels: documentation

#1128 chore(governance): update issue templates to use forms
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/DOC_IMPROVEMENT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/RFC.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation_improvements.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/ISSUE_TEMPLATE/share_your_work.yml
  .github/ISSUE_TEMPLATE/support_powertools.yml
Labels: internal

#1133 docs: main page updates around support
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/index.md
Labels: documentation

#1129 fix(metrics): metadata and dimensions not cleared on publish
  packages/metrics/src/Metrics.ts
  packages/metrics/tests/unit/Metrics.test.ts
Labels: bug
