Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-03, with the labels that each got.

#605 build(dev-deps): consolidate all common dev deps in workspaces
  package-lock.json
  package.json
  packages/commons/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/tracing/package.json
Labels: dependencies, internal

#604 docs: Add usage sub-section in docs
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
Labels: documentation, enhancement, utility:all

#615 chore(examples/cdk): Unpin CDK CLI in devDependencies of CDK examples
  examples/cdk/package.json
Labels: dependencies

#628 docs: updated project names to aws lambda power tools for typescript
  CONTRIBUTING.md
  README.md
  docs/index.md
  examples/cdk/README.md
  mkdocs.yml
  packages/commons/README.md
  packages/commons/package.json
  packages/logger/README.md
  packages/logger/package.json
  packages/metrics/README.md
  packages/metrics/package.json
  packages/tracing/README.md
  packages/tracing/package.json
Labels: documentation

#614 fix(logger): fix handling of additional log keys
  docs/core/logger.md
  packages/logger/examples/additional-keys.ts
  packages/logger/examples/errors.ts
  packages/logger/src/Logger.ts
  packages/logger/src/types/Logger.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
  packages/logger/tests/unit/Logger.test.ts
Labels: bug, utility:logger

#643 build(deps): updated dependencies in examples
  examples/cdk/package-lock.json
  examples/cdk/package.json
Labels: dependencies

#658 fix(logger): enable sequential invocation in e2e test
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/helpers/e2eUtils.ts
Labels: bug, utility:logger

#623 docs(all): add toc to README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#676 test(all): move e2e tests to cdk v2
  package-lock.json
  package.json
  packages/commons/tests/utils/cdk-cli.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/logger/tests/helpers/e2eUtils.ts
  packages/metrics/tests/e2e/decorator.test.ts
  packages/metrics/tests/e2e/standardFunctions.test.ts
  packages/tracing/tests/e2e/tracer.test.ts
Labels: internal

#678 test(common,logger,metrics): run e2e tests for metrics in both Node runtimes
  CONTRIBUTING.md
  package-lock.json
  packages/commons/tests/unit/InvocationLogs.test.ts
  packages/commons/tests/utils/InvocationLogs.ts
  packages/commons/tests/utils/e2eUtils.ts
  packages/logger/package.json
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/constants.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/metrics/package.json
  packages/metrics/tests/e2e/basicFeatures.decorator.test.functionCode.ts
  packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
  packages/metrics/tests/e2e/basicFeatures.manual.test.functionCode.ts
  packages/metrics/tests/e2e/basicFeatures.manual.test.ts
  packages/metrics/tests/e2e/constants.ts
  packages/metrics/tests/e2e/decorator.test.ts
  packages/metrics/tests/e2e/standardFunctions.test.ts
Labels: utility:metrics, internal
