Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-01, with the labels that each got.

#424 fix(metrics): Rename leftover reference to purgeStoredMetrics() function
  examples/cdk/lib/example-function.MyFunction.ts
  packages/metrics/tests/unit/Metrics.test.ts
Labels: bug

#416 refactor(metrics): rename option property from raiseOnEmptyMetrics to throwOnEmptyMetrics
  docs/core/metrics.md
  examples/cdk/lib/example-function.MyFunction.ts
  examples/cdk/lib/example-function.MyFunctionWithDecorator.ts
  packages/metrics/examples/decorator/empty-metrics.ts
  packages/metrics/examples/empty-metrics.ts
  packages/metrics/src/Metrics.ts
  packages/metrics/src/middleware/middy.ts
  packages/metrics/src/types/Metrics.ts
  packages/metrics/tests/e2e/decorator.test.MyFunction.ts
  packages/metrics/tests/e2e/standardFunctions.test.MyFunction.ts
  packages/metrics/tests/unit/Metrics.test.ts
  packages/metrics/tests/unit/middleware/middy.test.ts
Labels: enhancement, utility/metrics

#414 docs: Tracer example link goes to a 404
  README.md
  docs/index.md
  packages/commons/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/tracing/README.md
Labels: documentation

#440 fix(build): Fix linting issue and add linting to the pre-push hook
  .husky/pre-push
  packages/metrics/src/Metrics.ts
Labels: bug

#427 build(logger): reduce node_modules size
  package-lock.json
  package.json
  packages/logger/package-lock.json
  packages/logger/package.json
  packages/logger/src/Logger.ts
  packages/logger/src/log/LogItem.ts
  packages/logger/tests/unit/Logger.test.ts
Labels: dependencies, utility/logger

#442 fix(tracer): avoid throwing errors in manual instrumentation when running outside of AWS Lambda
  packages/tracing/src/Tracer.ts
  packages/tracing/tests/unit/Tracer.test.ts
Labels: bug, utility/tracer

#417 fix(build): Update contributing.md and fix npm ci
  CONTRIBUTING.md
  packages/commons/tsconfig.json
  packages/logger/tsconfig.json
  packages/metrics/tsconfig.json
  packages/tracing/tsconfig.json
Labels: documentation

#444 chore(all): fix doc typos and apply basic lint recommendations
  packages/logger/src/Logger.ts
  packages/logger/src/log/LogItemInterface.ts
  packages/logger/src/types/formats/PowertoolLog.ts
  packages/tracing/src/Tracer.ts
  packages/tracing/src/middleware/middy.ts
Labels: all, internal

#470 fix(all): fix latest release broken by change of npm pack result on common
  CONTRIBUTING.md
  packages/commons/tsconfig.json
  packages/logger/package-lock.json
  packages/logger/package.json
  packages/logger/tsconfig.json
  packages/metrics/package-lock.json
  packages/metrics/package.json
  packages/metrics/tsconfig.json
  packages/tracing/package-lock.json
  packages/tracing/package.json
  packages/tracing/tsconfig.json
Labels: bug

#439 fix: updated CDK examples to remove old references & improve comments
  examples/cdk/lib/example-function.MyFunction.ts
  examples/cdk/lib/example-function.MyFunctionWithDecorator.ts
  examples/cdk/lib/example-function.MyFunctionWithMiddy.ts
  examples/cdk/lib/example-function.Tracer.CaptureErrorDisabled.ts
  examples/cdk/lib/example-function.Tracer.CaptureResponseDisabled.ts
  examples/cdk/lib/example-function.Tracer.Decorator.ts
  examples/cdk/lib/example-function.Tracer.Disabled.ts
  examples/cdk/lib/example-function.Tracer.Manual.ts
  examples/cdk/lib/example-function.Tracer.Middleware.ts
  examples/cdk/lib/example-function.Tracer.PatchAWSSDKv2.ts
  examples/cdk/lib/example-function.Tracer.PatchAWSSDKv3.ts
  examples/cdk/lib/example-function.Tracer.PatchAllAWSSDK.ts
Labels: bug, documentation, all

#479 fix(logger): correctly export LogFormatter
  docs/core/logger.md
  packages/logger/src/index.ts
Labels: bug, utility/logger

#467 docs: Improve examples/cdk/README.md
  examples/cdk/README.md
  examples/cdk/bin/cdk-app.ts
  packages/metrics/src/Metrics.ts
  packages/metrics/tests/e2e/decorator.test.MyFunction.ts
  packages/metrics/tests/e2e/standardFunctions.test.MyFunction.ts
Labels: documentation

#480 chore(cicd): fix lerna version not bumping and publishing all packages
  .github/workflows/on-release-prod.yml
Labels: internal

#481 build(deps-dev): bump typedoc from 0.22.10 to 0.22.11
  package-lock.json
  package.json
Labels: dependencies, internal

#451 test(logger): added unit test for URIError
  packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
Labels: utility:logger

#453 docs: updated tenets section to conform w other runtimes
  docs/index.md
Labels: documentation

#446 chore(examples): integrate in CI flow with lint and build
  .github/workflows/run-e2e-tests.yml
  CONTRIBUTING.md
  examples/cdk/README.md
  examples/cdk/bin/cdk-app.ts
  examples/cdk/jest.config.js
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/cdk/src/example-function.MyFunction.ts
  examples/cdk/src/example-function.MyFunctionWithDecorator.ts
  examples/cdk/src/example-function.MyFunctionWithMiddy.ts
  examples/cdk/src/example-function.Tracer.CaptureErrorDisabled.ts
  examples/cdk/src/example-function.Tracer.CaptureResponseDisabled.ts
  examples/cdk/src/example-function.Tracer.Decorator.ts
  examples/cdk/src/example-function.Tracer.Disabled.ts
  examples/cdk/src/example-function.Tracer.Manual.ts
  examples/cdk/src/example-function.Tracer.Middleware.ts
  examples/cdk/src/example-function.Tracer.PatchAWSSDKv2.ts
  examples/cdk/src/example-function.Tracer.PatchAWSSDKv3.ts
  examples/cdk/src/example-function.Tracer.PatchAllAWSSDK.ts
  examples/cdk/src/example-function.ts
  examples/cdk/src/example-stack.ts
  examples/cdk/test/cdk-app.test.ts
  examples/cdk/tests/cdk-app.test.ts
  examples/cdk/tsconfig.json
  lerna.json
Labels: documentation, internal

#464 chore(cicd): fix trigger for gh actions linting andctesting PR from fork
  .github/workflows/pr_lint_and_test.yml
Labels: github-actions, internal

#472 docs(all): Fix docs and examples
  CONTRIBUTING.md
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/index.md
  examples/cdk/src/example-function.Tracer.CaptureErrorDisabled.ts
  examples/cdk/src/example-function.Tracer.CaptureResponseDisabled.ts
  packages/logger/src/Logger.ts
  packages/metrics/src/Metrics.ts
  packages/tracing/src/Tracer.ts
  typedoc.js
Labels: documentation

#491 feat(logger): JSDOCS support
  examples/cdk/src/example-function.MyFunctionWithMiddy.ts
  packages/logger/src/Logger.ts
  packages/logger/src/config/ConfigService.ts
  packages/logger/src/config/ConfigServiceInterface.ts
  packages/logger/src/config/EnvironmentVariablesService.ts
  packages/logger/src/formatter/LogFormatter.ts
  packages/logger/src/formatter/LogFormatterInterface.ts
  packages/logger/src/formatter/PowertoolLogFormatter.ts
  packages/logger/src/middleware/middy.ts
  packages/tracing/src/Tracer.ts
  packages/tracing/tests/unit/middy.test.ts
Labels: documentation, utility:logger, feature

#492 docs: improve dev setup & contributing info
  .nvmrc
  CONTRIBUTING.md
Labels: documentation

#498 chore(examples): fix version bumping of examples
  examples/cdk/package-lock.json
  examples/cdk/package.json
Labels: internal

#489 fix(logger|metrics): return decorated class
  packages/logger/src/Logger.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/types/LambdaInterface.ts
  packages/logger/types/Logger.ts
  packages/metrics/src/Metrics.ts
  packages/metrics/tests/unit/Metrics.test.ts
Labels: utility:logger, utility:metrics, fix

#485 feat: Add codespaces/gitpod support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitpod.yml
  CONTRIBUTING.md
Labels: feature

#450 feat(tracer): add support for capturing DynamoDB DocumentClient
  packages/tracing/package-lock.json
  packages/tracing/package.json
  packages/tracing/src/Tracer.ts
  packages/tracing/tests/e2e/tracer.test.Decorator.ts
  packages/tracing/tests/e2e/tracer.test.DecoratorWithAsyncHandler.ts
  packages/tracing/tests/e2e/tracer.test.Manual.ts
  packages/tracing/tests/e2e/tracer.test.Middleware.ts
  packages/tracing/tests/e2e/tracer.test.ts
  packages/tracing/tests/helpers/tracesUtils.ts
  packages/tracing/tests/unit/Tracer.test.ts
Labels: enhancement, utility:tracer, feature

#511 feat(all): make `@middy/core` optional
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  examples/cdk/package-lock.json
  examples/cdk/package.json
  packages/logger/package-lock.json
  packages/logger/package.json
  packages/logger/src/middleware/middy.ts
  packages/metrics/package-lock.json
  packages/metrics/package.json
  packages/metrics/src/middleware/middy.ts
  packages/tracing/package-lock.json
  packages/tracing/package.json
  packages/tracing/src/middleware/middy.ts
Labels: dependencies, utility:all, feature

#509 fix(examples): fix errors in logger and metrics examples
  README.md
  examples/cdk/src/example-function.Tracer.PatchAWSSDKv2.ts
  examples/cdk/src/example-function.Tracer.PatchAWSSDKv3.ts
  examples/cdk/src/example-function.Tracer.PatchAllAWSSDK.ts
  packages/logger/examples/ephemeral-attributes.ts
  packages/logger/examples/inject-context-decorator.ts
  packages/logger/examples/inject-context-middleware.ts
  packages/logger/examples/utils/formatters/CustomLogFormatter.ts
  packages/logger/examples/utils/formatters/MyCompanyLogFormatter.ts
  packages/metrics/examples/cold-start.ts
  packages/metrics/examples/constructor-options.ts
  packages/metrics/examples/decorator/cold-start.ts
  packages/metrics/examples/decorator/constructor-options.ts
  packages/metrics/examples/decorator/default-dimensions-constructor.ts
  packages/metrics/examples/decorator/default-dimensions.ts
  packages/metrics/examples/decorator/dimensions.ts
  packages/metrics/examples/decorator/empty-metrics.ts
  packages/metrics/examples/decorator/hello-world.ts
  packages/metrics/examples/decorator/manual-flushing.ts
  packages/metrics/examples/decorator/manual-metrics-print.ts
  packages/metrics/examples/decorator/single-metric.ts
  packages/metrics/examples/default-dimensions-constructor.ts
  packages/metrics/examples/default-dimensions.ts
  packages/metrics/examples/dimensions.ts
  packages/metrics/examples/empty-metrics.ts
  packages/metrics/examples/hello-world.ts
  packages/metrics/examples/manual-flushing.ts
  packages/metrics/examples/manual-metrics-print.ts
  packages/metrics/examples/single-metric.ts
Labels: bug
