Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-02, with the labels that each got.

#528 fix(tracer): properly return DynamoDB.DocumentClient
  packages/tracing/src/Tracer.ts
  packages/tracing/tests/e2e/tracer.test.Decorator.ts
  packages/tracing/tests/e2e/tracer.test.DecoratorWithAsyncHandler.ts
  packages/tracing/tests/e2e/tracer.test.Manual.ts
  packages/tracing/tests/e2e/tracer.test.Middleware.ts
  packages/tracing/tests/e2e/tracer.test.ts
  packages/tracing/tests/unit/Tracer.test.ts
Labels: bug, utility:tracer, fix

#529 feat(logger): add e2e tests for logger
  CONTRIBUTING.md
  packages/logger/package-lock.json
  packages/logger/package.json
  packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.FunctionCode.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.FunctionCode.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/logger/tests/helpers/InvocationLogs.ts
  packages/logger/tests/helpers/e2eUtils.ts
Labels: feature

#534 docs(theme): upgrade mkdocs material to 8.x
  .gitignore
  docs/overrides/assets/images/powertools_docs_thumbnail.png
  docs/overrides/main.html
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, dependencies

#559 chore(logger): make Logger E2E works for all runtimes
  packages/logger/package-lock.json
  packages/logger/package.json
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/logger/tests/helpers/e2eUtils.ts
Labels: internal

#547 feat(commons): centralize cold start heuristic
  packages/commons/src/Utility.ts
  packages/commons/src/index.ts
  packages/commons/tests/unit/LambdaInterface.test.ts
  packages/commons/tests/unit/Utility.test.ts
Labels: enhancement, utility:all, feature

#562 chore(all): Switch to use only eu-west-1 in tests and doc
  docs/core/logger.md
  packages/commons/src/tests/resources/contexts/hello-world.ts
  packages/logger/examples/persistent-attributes.ts
  packages/logger/package.json
  packages/logger/tests/helpers/InvocationLogs.ts
  packages/logger/tests/helpers/populateEnvironmentVariables.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
  packages/logger/tests/unit/helpers.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
  packages/metrics/tests/unit/middleware/middy.test.ts
  packages/tracing/tests/unit/Tracer.test.ts
  packages/tracing/tests/unit/middy.test.ts
  tests/resources/contexts/hello-world.ts
Labels: internal

#548 feat(metrics): adopted Utility class
  docs/core/metrics.md
  packages/metrics/package-lock.json
  packages/metrics/package.json
  packages/metrics/src/Metrics.ts
Labels: enhancement, utility:metrics, feature

#549 feat(tracer): adopted Utility class & updated unit tests
  docs/core/tracer.md
  packages/tracing/package-lock.json
  packages/tracing/package.json
  packages/tracing/src/Tracer.ts
  packages/tracing/tests/unit/Tracer.test.ts
  packages/tracing/tests/unit/middy.test.ts
Labels: enhancement, utility:tracer, feature

#572 improv: github issues template, RFC added
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/DOC_IMPROVEMENT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/RFC.md
Labels: internal

#573 docs: added summary section to contributing docs
  CONTRIBUTING.md
Labels: documentation

#570 chore: update actions to npm8
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on-release-prod.yml
  .github/workflows/pr_lint_and_test.yml
  .github/workflows/run-e2e-tests.yml
  CONTRIBUTING.md
  package.json
Labels: internal

#569 chore: updated dependencies
  package-lock.json
  packages/commons/package-lock.json
  packages/commons/package.json
  packages/logger/package-lock.json
  packages/logger/package.json
  packages/metrics/package-lock.json
  packages/metrics/package.json
  packages/tracing/package-lock.json
  packages/tracing/package.json
Labels: internal

#550 feat(logger): adopted Utility class & updated unit tests
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on-release-prod.yml
  .github/workflows/pr_lint_and_test.yml
  .github/workflows/run-e2e-tests.yml
  docs/core/logger.md
  package-lock.json
  package.json
  packages/logger/package.json
  packages/logger/src/Logger.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/helpers.test.ts
Labels: enhancement, utility:logger, feature
