Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-05, with the labels that each got.

#674 docs(examples): add example for AWS SAM
  .gitignore
  examples/lambda-functions/get-all-items.ts
  examples/lambda-functions/get-by-id.ts
  examples/lambda-functions/put-item.ts
  examples/lambda-functions/tsconfig.json
  examples/sam/.gitignore
  examples/sam/README.md
  examples/sam/events/event-get-all-items.json
  examples/sam/events/event-get-by-id.json
  examples/sam/events/event-post-item.json
  examples/sam/package.json
  examples/sam/src/handlers
  examples/sam/template.yaml
Labels: documentation

#828 test(all): switch to use GitHub strategy matrix and fix flaky tests
  .github/workflows/run-e2e-tests.yml
  package-lock.json
  packages/commons/tests/utils/e2eUtils.ts
  packages/logger/package.json
  packages/logger/tests/e2e/constants.ts
  packages/metrics/package.json
  packages/metrics/tests/e2e/constants.ts
  packages/tracing/package.json
  packages/tracing/tests/e2e/constants.ts
  packages/tracing/tests/helpers/FunctionSegmentNotDefinedError.ts
  packages/tracing/tests/helpers/tracesUtils.ts
Labels: internal

#848 fix(actions): reintroduce token to checkout repo in release workflow
  .github/workflows/on-release-prod.yml
Labels: bug, github-actions, internal

#854 chore(tracer): rename package folder to tracer
  .github/workflows/run-e2e-tests.yml
  package-lock.json
  package.json
  packages/tracer/CHANGELOG.md
  packages/tracer/LICENSE-THIRD-PARTY
  packages/tracer/README.md
  packages/tracer/jest.config.js
  packages/tracer/package.json
  packages/tracer/src/Tracer.ts
  packages/tracer/src/TracerInterface.ts
  packages/tracer/src/config/ConfigService.ts
  packages/tracer/src/config/ConfigServiceInterface.ts
  packages/tracer/src/config/EnvironmentVariablesService.ts
  packages/tracer/src/config/index.ts
  packages/tracer/src/helpers.ts
  packages/tracer/src/index.ts
  packages/tracer/src/middleware/middy.ts
  packages/tracer/src/provider/ProviderService.ts
  packages/tracer/src/provider/ProviderServiceInterface.ts
  packages/tracer/src/provider/index.ts
  packages/tracer/src/types/Tracer.ts
  packages/tracer/src/types/index.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
  packages/tracer/tests/e2e/constants.ts
  packages/tracer/tests/helpers/FunctionSegmentNotDefinedError.ts
  packages/tracer/tests/helpers/populateEnvironmentVariables.ts
  packages/tracer/tests/helpers/traceAssertions.ts
  packages/tracer/tests/helpers/tracesUtils.ts
  packages/tracer/tests/unit/ProviderService.test.ts
  packages/tracer/tests/unit/Tracer.test.ts
  packages/tracer/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/tracer/tests/unit/helpers.test.ts
  packages/tracer/tests/unit/middy.test.ts
  packages/tracer/tsconfig.es.json
  packages/tracer/tsconfig.json
Labels: utility:tracer, internal

#883 fix(logger): enable logging of arbitrary objects
  docs/core/logger.md
  packages/logger/examples/additional-keys.ts
  packages/logger/src/types/Log.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/unit/Logger.test.ts
Labels: bug, utility:logger

#877 feat(all): nodejs16x support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on-release-prod.yml
  .github/workflows/pr_lint_and_test.yml
  .github/workflows/run-e2e-tests.yml
  .nvmrc
  CONTRIBUTING.md
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  examples/cdk/src/example-function.ts
  examples/sam/template.yaml
  package.json
  packages/commons/tests/utils/e2eUtils.ts
  packages/logger/package.json
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/metrics/package.json
  packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
  packages/metrics/tests/e2e/basicFeatures.manual.test.ts
  packages/tracer/package.json
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
  packages/tracer/tests/helpers/populateEnvironmentVariables.ts
  packages/tracer/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/tracer/tests/unit/helpers.test.ts
Labels: feature

#876 chore(examples): updated contributing & docs with SAM
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .gitpod.yml
  CONTRIBUTING.md
  README.md
  docs/index.md
  packages/commons/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/tracer/README.md
Labels: documentation, internal

#901 feat(logger): add removeKeys functionality
  CONTRIBUTING.md
  docs/core/logger.md
  package.json
  packages/logger/src/Logger.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/unit/Logger.test.ts
Labels: feature
