Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2022-07, with the labels that each got.

#1011 docs: added note about active tracing
  docs/core/tracer.md
Labels: documentation, utility:tracer

#1010 feat(tracer): auto disable when running inside amplify mock
  docs/core/tracer.md
  packages/tracer/src/Tracer.ts
  packages/tracer/tests/unit/helpers.test.ts
Labels: feature

#1015 fix(logger): POWERTOOLS_LOGGER_LOG_EVENT precedence is respected
  packages/logger/src/Logger.ts
  packages/logger/src/middleware/middy.ts
  packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
Labels: bug, utility:logger, fix

#1016 fix(tracer): capture method throws errors correctly
  packages/tracer/src/Tracer.ts
  packages/tracer/tests/unit/Tracer.test.ts
Labels: bug, utility:tracer, fix

#1020 chore(docs): bump version in examples
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/sam/package-lock.json
  examples/sam/package.json
Labels: internal

#1021 docs: minor improvements
  README.md
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/index.md
  docs/stylesheets/extra.css
  mkdocs.yml
  packages/logger/README.md
  packages/metrics/README.md
  packages/tracer/README.md
Labels: documentation

#1022 docs: minor improvements and fixes
  README.md
  docs/Dockerfile
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/index.md
  docs/media/logger_utility_showcase.png
  docs/media/metrics_utility_showcase.png
  docs/media/tracer_utility_showcase.png
  docs/media/tracer_utility_showcase_2.png
  docs/requirements.txt
  mkdocs.yml
  packages/logger/README.md
  packages/metrics/README.md
  packages/tracer/README.md
Labels: documentation

#1026 fix: wrong scope in captureMethod
  packages/tracer/src/Tracer.ts
  packages/tracer/tests/unit/Tracer.test.ts
Labels: utility:logger, fix
