Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-12, with the labels that each got.

#1815 feat(parser): add schema envelopes
  .husky/pre-push
  package-lock.json
  packages/parser/package.json
  packages/parser/src/envelopes/apigw.ts
  packages/parser/src/envelopes/apigwv2.ts
  packages/parser/src/envelopes/cloudwatch.ts
  packages/parser/src/envelopes/dynamodb.ts
  packages/parser/src/envelopes/envelope.ts
  packages/parser/src/envelopes/eventbridge.ts
  packages/parser/src/envelopes/kafka.ts
  packages/parser/src/envelopes/kinesis-firehose.ts
  packages/parser/src/envelopes/kinesis.ts
  packages/parser/src/envelopes/lambda.ts
  packages/parser/src/envelopes/sns.ts
  packages/parser/src/envelopes/sqs.ts
  packages/parser/src/envelopes/vpc-lattice.ts
  packages/parser/src/envelopes/vpc-latticev2.ts
  packages/parser/src/schemas/cloudwatch.ts
  packages/parser/src/schemas/kafka.ts
  packages/parser/src/schemas/kinesis.ts
  packages/parser/src/schemas/sns.ts
  packages/parser/src/types/index.ts
  packages/parser/src/types/schema.ts
  packages/parser/tests/unit/envelopes/apigwt.test.ts
  packages/parser/tests/unit/envelopes/apigwv2.test.ts
  packages/parser/tests/unit/envelopes/cloudwatch.test.ts
  packages/parser/tests/unit/envelopes/dynamodb.test.ts
  packages/parser/tests/unit/envelopes/eventbridge.test.ts
  packages/parser/tests/unit/envelopes/kafka.test.ts
  packages/parser/tests/unit/envelopes/kinesis-firehose.test.ts
  packages/parser/tests/unit/envelopes/kinesis.test.ts
  packages/parser/tests/unit/envelopes/lambda.test.ts
  packages/parser/tests/unit/envelopes/sns.test.ts
  packages/parser/tests/unit/envelopes/sqs.test.ts
  packages/parser/tests/unit/envelopes/vpc-lattice.test.ts
  packages/parser/tests/unit/envelopes/vpc-latticev2.test.ts
  packages/parser/tests/unit/schema/alb.test.ts
  packages/parser/tests/unit/schema/apigw.test.ts
  packages/parser/tests/unit/schema/apigwv2.test.ts
  packages/parser/tests/unit/schema/cloudformation-custom-resource.test.ts
  packages/parser/tests/unit/schema/cloudwatch.test.ts
  packages/parser/tests/unit/schema/dynamodb.test.ts
  packages/parser/tests/unit/schema/eventbridge.test.ts
  packages/parser/tests/unit/schema/kafka.test.ts
  packages/parser/tests/unit/schema/kinesis.test.ts
  packages/parser/tests/unit/schema/lambda.test.ts
  packages/parser/tests/unit/schema/s3.test.ts
  packages/parser/tests/unit/schema/ses.test.ts
  packages/parser/tests/unit/schema/sns.test.ts
  packages/parser/tests/unit/schema/sqs.test.ts
  packages/parser/tests/unit/schema/utils.ts
  packages/parser/tests/unit/schema/vpc-lattice.test.ts
  packages/parser/tests/unit/schema/vpc-latticev2.test.ts
Labels: type/dependencies, type/internal, size/XXL, type/feature, type/tests, area/parser

#1821 docs(logger): remove logEvent from required settings
  docs/core/logger.md
Labels: area/documentation, size/S

#1823 feat(parser): implement middy parser middleware
  packages/parser/src/envelopes/event-bridge.ts
  packages/parser/src/middleware/parser.ts
  packages/parser/src/types/envelope.ts
  packages/parser/tests/unit/envelopes/eventbridge.test.ts
  packages/parser/tests/unit/parser.test.ts
Labels: size/L, type/feature, type/tests, area/parser

#1826 chore(docs): add AppYourself reference customer
  README.md
  docs/index.md
  docs/media/logos/appyourself.svg
  packages/batch/README.md
  packages/commons/README.md
  packages/idempotency/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/tracer/README.md
Labels: area/documentation, type/internal, size/M

#1827 chore(maintenance): add `--require-hashes` flag to pip installs
  .github/workflows/reusable-publish-docs.yml
  docs/Dockerfile
  docs/docker-requirements.txt
  docs/requirements.out
  docs/requirements.txt
  mkdocs.yml
Labels: area/documentation, area/automation, size/XL

#1830 docs: fix deps and build
  docs/Dockerfile
  docs/requirements.in
  docs/requirements.txt
Labels: area/documentation, size/L

#1831 feat(parser): implement parser decorator
  packages/parser/src/middleware/parser.ts
  packages/parser/src/parser.ts
  packages/parser/src/types/ParserOptions.ts
  packages/parser/tests/unit/parser.decorator.test.ts
  packages/parser/tests/unit/parser.middy.test.ts
Labels: size/L, type/feature, type/tests, area/parser

#1824 docs: fix some typos
  docs/core/logger.md
  docs/core/tracer.md
  docs/maintainers.md
Labels: area/documentation, type/internal, size/XS
