Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-03, with the labels that each got.

#1347 feat(logger): add silent log level to suppress the emission of all logs
  docs/core/logger.md
  packages/logger/src/Logger.ts
  packages/logger/src/types/Log.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/helpers.test.ts
Labels: size/L, type/feature

#1358 chore(docs): updated layer info
  docs/index.md
Labels: type/internal, size/S

#1364 chore(examples): fix cdk cleanup command
  examples/cdk/README.md
Labels: type/bug, area/documentation, type/internal, size/XS

#1360 chore(ci): added lint-staged as pre-commit hook
  .husky/pre-commit
  docs/snippets/package.json
  examples/cdk/package.json
  examples/sam/package.json
  layers/package.json
  package-lock.json
  package.json
  packages/commons/package.json
  packages/idempotency/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/parameters/package.json
  packages/tracer/package.json
Labels: type/internal, size/M

#1365 feat(parameters): AppConfigProvider to return the last valid value when the API returns empty value on subsequent calls
  packages/commons/tests/utils/e2eUtils.ts
  packages/parameters/src/appconfig/AppConfigProvider.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.ts
  packages/parameters/tests/unit/AppConfigProvider.test.ts
Labels: size/L, type/feature

#1370 refactor(tracer): log warning instead of throwing when segment is not found
  package-lock.json
  packages/tracer/package.json
  packages/tracer/src/Tracer.ts
  packages/tracer/src/TracerInterface.ts
  packages/tracer/src/middleware/middy.ts
  packages/tracer/src/provider/ProviderService.ts
  packages/tracer/src/provider/ProviderServiceInterface.ts
  packages/tracer/tests/unit/ProviderService.test.ts
  packages/tracer/tests/unit/Tracer.test.ts
  packages/tracer/tests/unit/middy.test.ts
Labels: size/XL, type/feature

#1382 feat(parameters): add `clearCaches` function
  packages/parameters/src/BaseProvider.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
Labels: size/M, type/feature

#1383 docs(parameters): add "testing your code" section
  docs/snippets/package.json
  docs/snippets/parameters/testingYourCodeClearCache.ts
  docs/snippets/parameters/testingYourCodeClientHandler.ts
  docs/snippets/parameters/testingYourCodeClientJestMock.ts
  docs/snippets/parameters/testingYourCodeFunctionsHandler.ts
  docs/snippets/parameters/testingYourCodeFunctionsJestMock.ts
  docs/snippets/parameters/testingYourCodeProvidersHandler.ts
  docs/snippets/parameters/testingYourCodeProvidersJestMock.ts
  docs/utilities/parameters.md
  package-lock.json
Labels: area/documentation, size/L

#1372 chore(layer): add license and architecture fields
  layers/src/layer-publisher-stack.ts
  layers/tests/unit/layer-publisher.test.ts
Labels: type/internal, size/S

#1388 fix(parameters): fix import path to use relative paths
  packages/parameters/src/types/AppConfigProvider.ts
Labels: type/bug, area/parameters, size/XS

#1384 feat(parameters): ability to set `maxAge` and `decrypt` via environment variables
  docs/index.md
  docs/snippets/parameters/adjustingCacheTTL.ts
  docs/snippets/parameters/ssmProviderDecryptAndRecursive.ts
  docs/utilities/parameters.md
  package-lock.json
  packages/commons/src/config/ConfigService.ts
  packages/commons/src/config/EnvironmentVariablesService.ts
  packages/commons/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/logger/src/config/EnvironmentVariablesService.ts
  packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/parameters/package.json
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/GetMultipleOptions.ts
  packages/parameters/src/GetOptions.ts
  packages/parameters/src/appconfig/AppConfigProvider.ts
  packages/parameters/src/config/ConfigServiceInterface.ts
  packages/parameters/src/config/EnvironmentVariablesService.ts
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/tests/unit/SSMProvider.test.ts
  packages/parameters/tests/unit/config/EnvironmentVariablesService.test.ts
Labels: area/parameters, size/L, type/feature

#1376 feat(idempotency): BasePersistenceLayer, DynamoDBPersistenceLayer and configs
  package-lock.json
  packages/idempotency/package-lock.json
  packages/idempotency/package.json
  packages/idempotency/src/Exceptions.ts
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/config/EnvironmentVariablesService.ts
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/src/makeFunctionIdempotent.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/src/persistence/BasePersistenceLayerInterface.ts
  packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
  packages/idempotency/src/persistence/IdempotencyRecord.ts
  packages/idempotency/src/persistence/PersistenceLayer.ts
  packages/idempotency/src/persistence/index.ts
  packages/idempotency/src/types/AnyFunction.ts
  packages/idempotency/src/types/BasePersistenceLayer.ts
  packages/idempotency/src/types/DynamoDBPersistence.ts
  packages/idempotency/src/types/DynamoPersistenceConstructorOptions.ts
  packages/idempotency/src/types/IdempotencyOptions.ts
  packages/idempotency/src/types/IdempotencyRecord.ts
  packages/idempotency/src/types/IdempotencyRecordStatus.ts
  packages/idempotency/src/types/PersistenceLayer.ts
  packages/idempotency/src/types/index.ts
  packages/idempotency/tests/unit/IdempotencyConfig.test.ts
  packages/idempotency/tests/unit/config/EnvironmentVariableService.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/IdempotencyRecord.test.ts
  packages/idempotency/tests/unit/persistence/PersistenceLayer.test.ts
Labels: size/XXL, type/feature

#1390 chore: add new label for stale automation
  .github/workflows/stale-issues.yml
  MAINTAINERS.md
Labels: type/internal, size/S

#1391 chore(ci): convert deprecated `set-output` command
  .github/workflows/measure-packages-size.yml
  .github/workflows/reusable_export_pr_details.yml
Labels: type/internal, size/S
