Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-02, with the labels that each got.

#1260 feat(parameters): add support for custom AWS SDK v3 clients for providers
  packages/parameters/src/appconfig/AppConfigProvider.ts
  packages/parameters/src/dynamodb/DynamoDBProvider.ts
  packages/parameters/src/secrets/SecretsProvider.ts
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/types/AppConfigProvider.ts
  packages/parameters/src/types/DynamoDBProvider.ts
  packages/parameters/src/types/SSMProvider.ts
  packages/parameters/src/types/SecretsProvider.ts
  packages/parameters/tests/unit/AppConfigProvider.test.ts
  packages/parameters/tests/unit/DynamoDBProvider.test.ts
  packages/parameters/tests/unit/SSMProvider.test.ts
  packages/parameters/tests/unit/SecretsProvider.test.ts
Labels: size/L, type/feature

#1262 feat(idempotency): Add function wrapper and decorator
  package-lock.json
  package.json
  packages/idempotency/src/Exceptions.ts
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/src/makeFunctionIdempotent.ts
  packages/idempotency/src/types/AnyFunction.ts
  packages/idempotency/src/types/index.ts
  packages/idempotency/tests/helpers/populateEnvironmentVariables.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
Labels: area/idempotency, size/L, type/feature

#1266 chore: integrate parameters into CI/CD package measurement
  .github/workflows/measure-packages-size.yml
Labels: type/internal, size/XS

#1263 tests(parameters): integration tests for `SecretsProvider`
  packages/parameters/tests/e2e/secretsProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/secretsProvider.class.test.ts
  packages/parameters/tests/helpers/cdkAspectGrantAccess.ts
Labels: area/parameters, size/L, type/tests

#1259 refactor(docs): apply eslint rules to code snippets
  .eslintrc.js
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  docs/snippets/logger/appendKeys.ts
  docs/snippets/logger/basicUsage.ts
  docs/snippets/logger/bringYourOwnFormatterClass.ts
  docs/snippets/logger/bringYourOwnFormatterHandler.ts
  docs/snippets/logger/clearStateDecorator.ts
  docs/snippets/logger/clearStateMiddy.ts
  docs/snippets/logger/createChild.ts
  docs/snippets/logger/decorator.ts
  docs/snippets/logger/eventDecorator.ts
  docs/snippets/logger/eventMiddy.ts
  docs/snippets/logger/extraData.ts
  docs/snippets/logger/logError.ts
  docs/snippets/logger/logSampling.ts
  docs/snippets/logger/manual.ts
  docs/snippets/logger/middy.ts
  docs/snippets/logger/sam.ts
  docs/snippets/logger/unitTesting.ts
  docs/snippets/metrics/addMetadata.ts
  docs/snippets/metrics/basicUsage.ts
  docs/snippets/metrics/captureColdStartMetricDecorator.ts
  docs/snippets/metrics/captureColdStartMetricMiddy.ts
  docs/snippets/metrics/createMetrics.ts
  docs/snippets/metrics/customDimensions.ts
  docs/snippets/metrics/decorator.ts
  docs/snippets/metrics/defaultDimensions.ts
  docs/snippets/metrics/defaultDimensionsDecorator.ts
  docs/snippets/metrics/defaultDimensionsMiddy.ts
  docs/snippets/metrics/manual.ts
  docs/snippets/metrics/middy.ts
  docs/snippets/metrics/multiValueMetrics.ts
  docs/snippets/metrics/sam.ts
  docs/snippets/metrics/setDefaultDimensions.ts
  docs/snippets/metrics/singleMetricDifferentDimsDecorator.ts
  docs/snippets/metrics/singleMetricDifferentDimsMiddy.ts
  docs/snippets/metrics/throwOnEmptyMetrics.ts
  docs/snippets/package.json
  docs/snippets/tracer/accessRootTraceId.ts
  docs/snippets/tracer/basicUsage.ts
  docs/snippets/tracer/captureAWS.ts
  docs/snippets/tracer/captureAWSAll.ts
  docs/snippets/tracer/captureAWSv3.ts
  docs/snippets/tracer/captureHTTP.ts
  docs/snippets/tracer/captureMethodDecorator.ts
  docs/snippets/tracer/captureMethodManual.ts
  docs/snippets/tracer/decorator.ts
  docs/snippets/tracer/disableCaptureResponseHandler.ts
  docs/snippets/tracer/disableCaptureResponseMethod.ts
  docs/snippets/tracer/disableCaptureResponseMiddy.ts
  docs/snippets/tracer/manual.ts
  docs/snippets/tracer/middy.ts
  docs/snippets/tracer/putAnnotation.ts
  docs/snippets/tracer/putMetadata.ts
  docs/snippets/tracer/sam.ts
  package-lock.json
Labels: type/internal, size/XL, type/feature

#1274 chore(docs): moved docs/snippets checks to separate step
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
Labels: area/automation, type/internal, size/M

#1282 tests(parameters): add comments to `SecretsProvider` e2e test
  packages/parameters/tests/e2e/secretsProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/secretsProvider.class.test.ts
Labels: size/L, type/tests

#1284 docs(examples): made SAM CLI version requirement more explicit
  examples/sam/README.md
Labels: area/documentation, size/XS

#1285 tests(parameters): added missing tests for `DynamoDBProvider`
  packages/parameters/tests/e2e/dynamoDBProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/dynamoDBProvider.class.test.ts
Labels: area/parameters, size/L, type/tests

#1286 docs(logger): update child logger docs section and snippets
  docs/core/logger.md
  docs/snippets/logger/createChild.ts
Labels: area/documentation, size/S

#1290 chore(docs): update project's description
  docs/index.md
  packages/commons/README.md
  packages/idempotency/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/tracer/README.md
Labels: size/S

#1257 tests(parameters): integration tests for `SSMProvider`
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/ssm/index.ts
  packages/parameters/tests/e2e/dynamoDBProvider.class.test.ts
  packages/parameters/tests/e2e/ssmProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/ssmProvider.class.test.ts
  packages/parameters/tests/helpers/cdkAspectGrantAccess.ts
  packages/parameters/tests/helpers/parametersUtils.ts
  packages/parameters/tests/helpers/ssmSecureStringCdk.ts
Labels: area/parameters, size/XL, type/tests

#1312 chore: remove unused extensions from Gitpod/CodeSpaces
  .devcontainer/devcontainer.json
  .gitpod.yml
Labels: type/internal, size/XS

#1292 chore(layers): moved `layer-publisher` into npm workspace
  .github/scripts/setup_tmp_layer_files.sh
  .github/workflows/publish_layer.yaml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  .github/workflows/run-e2e-tests.yml
  .gitignore
  .husky/pre-commit
  .husky/pre-push
  layer-publisher/jest.config.js
  layer-publisher/package-lock.json
  layer-publisher/package.json
  layer-publisher/src/powertools-typescript-layer.ts
  layer-publisher/tests/e2e/happy-case.test.lambda.ts
  layer-publisher/tests/e2e/happy-case.test.ts
  layer-publisher/tests/unit/__snapshots__/layer-publisher.test.ts.snap
  layer-publisher/tests/unit/layer-publisher.test.ts
  layers/.eslintrc.js
  layers/.gitignore
  layers/.npmignore
  layers/CHANGELOG.md
  layers/README.md
  layers/bin/layers.ts
  layers/cdk.json
  layers/jest.config.js
  layers/package.json
  layers/src/layer-publisher-stack.ts
  layers/tests/e2e/constants.ts
  layers/tests/e2e/layerPublisher.class.test.functionCode.ts
  layers/tests/e2e/layerPublisher.test.ts
  layers/tests/helpers/populateEnvironmentVariables.ts
  layers/tests/unit/layer-publisher.test.ts
  layers/tsconfig.es.json
  layers/tsconfig.json
  package-lock.json
  package.json
  packages/commons/tests/utils/e2eUtils.ts
Labels: type/internal, size/XL

#1287 tests(parameters): integration tests for `AppConfigProvider`
  packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.ts
  packages/parameters/tests/helpers/cdkAspectGrantAccess.ts
  packages/parameters/tests/helpers/parametersUtils.ts
  packages/parameters/tests/helpers/sdkMiddlewareRequestCounter.ts
Labels: area/parameters, size/XL, type/tests

#1317 refactor(parameters): move table seeding into `AwsCustomResource`
  packages/parameters/tests/e2e/dynamoDBProvider.class.test.ts
  packages/parameters/tests/helpers/parametersUtils.ts
Labels: size/L, type/tests

#1318 tests(parameters): update package to run as part of e2e tests
  .github/workflows/run-e2e-tests.yml
  packages/parameters/package.json
Labels: size/XS

#1319 refactor(parameters): moved ssm resource creation to `AwsCustomResource`
  packages/parameters/tests/e2e/ssmProvider.class.test.ts
  packages/parameters/tests/helpers/parametersUtils.ts
  packages/parameters/tests/helpers/ssmSecureStringCdk.ts
Labels: size/L, type/tests

#1326 fix(parameters): handle base64/binaries in transformer
  packages/parameters/src/BaseProvider.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tests/unit/getAppConfig.test.ts
Labels: type/bug, size/L

#1322 feat(layers): add new regions
  .github/workflows/reusable_deploy_layer_stack.yml
  .husky/pre-push
  docs/index.md
  layers/README.md
Labels: size/L, type/feature

#1327 chore(layers): fix workflow + linting/housekeeping
  .github/workflows/reusable_deploy_layer_stack.yml
  docs/index.md
  layers/README.md
Labels: type/internal, size/S

#1324 chore(ci): automatically update docs after layer publish during release
  .github/scripts/update_layer_arn.sh
  .github/workflows/make-release.yml
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on_doc_merge.yml
  .github/workflows/publish-docs-on-release.yml
  .github/workflows/publish_layer.yaml
  .github/workflows/reusable-publish-docs.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  .github/workflows/reusable_update_layer_arn_docs.yml
Labels: type/internal, size/L

#1333 chore(ci): fixed workflow dependencies
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on_doc_merge.yml
Labels: size/XS

#1336 chore: revisited issue & PR templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/M

#1338 chore: updated `homepage` field in `package.json` files
  packages/commons/package.json
  packages/idempotency/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/tracer/package.json
Labels: type/internal, size/S

#1339 tests(logger): revisit Logger unit tests
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
  packages/logger/tests/unit/helpers.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
Labels: area/logger, size/XL, type/tests

#1329 fix(logger): middleware stores initial persistent attributes correctly
  packages/logger/src/middleware/middy.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
Labels: type/bug, size/L

#1335 chore(ci): pin 3rd party actions to sha commit
  .github/workflows/make-release.yml
  .github/workflows/measure-packages-size.yml
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on-workflows-push-pr.yml
  .github/workflows/publish_layer.yml
  .github/workflows/reusable-publish-docs.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  .github/workflows/run-e2e-tests.yml
Labels: area/automation, type/internal, size/M

#1313 feat(logger): make loglevel types stricter
  packages/logger/src/Logger.ts
  packages/logger/src/types/Log.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
  packages/logger/tests/unit/helpers.test.ts
Labels: size/M, type/feature

#1341 chore(ci): revisit stale issues automation
  .github/stale.yml
  .github/workflows/on-workflows-push-pr.yml
  .github/workflows/stale-issues.yml
  MAINTAINERS.md
Labels: type/internal, size/M

#1342 tests(logger): revisited integration tests
  packages/commons/tests/utils/InvocationLogs.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.FunctionCode.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/constants.ts
  packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.FunctionCode.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/logger/tests/helpers/types.ts
Labels: size/XL

#1346 chore(ci): narrow down stale issue filtering
  .github/workflows/stale-issues.yml
  MAINTAINERS.md
Labels: type/internal, size/S

#1349 chore(ci): fix typo in doc publishing workflow
  .github/workflows/on_doc_merge.yml
  .github/workflows/reusable-publish-docs.yml
Labels: type/internal, size/XS

#1351 chore: add disclaimer to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type/internal, size/XS
