Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-05, with the labels that each got.

#1427 chore(docs): add Elva partner + logo
  README.md
  docs/index.md
  docs/media/logos/elva.png
  packages/commons/README.md
  packages/idempotency/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/tracer/README.md
Labels: type/internal, size/XS

#1429 chore(docs): fix external links in `README` files
  README.md
  packages/commons/README.md
  packages/idempotency/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/tracer/README.md
Labels: size/M

#1434 chore(docs): bring examples into npm workspace
  .github/actions/cached-node-modules/action.yml
  .github/workflows/make-release.yml
  .github/workflows/publish_layer.yml
  .github/workflows/reusable-publish-docs.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  examples/cdk/.eslintrc.js
  examples/cdk/.gitignore
  examples/cdk/.npmignore
  examples/cdk/CHANGELOG.md
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/sam/.gitignore
  examples/sam/package-lock.json
  examples/sam/package.json
  package-lock.json
  package.json
Labels: type/internal, size/XL

#1435 feat(tracer): add isTraceSampled method
  packages/commons/src/config/EnvironmentVariablesService.ts
  packages/commons/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/tracer/src/Tracer.ts
  packages/tracer/src/TracerInterface.ts
  packages/tracer/tests/unit/Tracer.test.ts
Labels: size/L

#1431 chore(ci): improve PR, Issues, and release automations
  .github/PULL_REQUEST_TEMPLATE.md
  .github/boring-cyborg.yml
  .github/scripts/constants.js
  .github/scripts/label_missing_related_issue.js
  .github/scripts/label_pr_based_on_title.js
  .github/scripts/label_related_issue.js
  .github/scripts/post_release.js
  .github/semantic.yml
  .github/workflows/post-release.yml
  MAINTAINERS.md
Labels: type/internal, size/XL

#1437 chore(ci): fix regex & if statement in related issue script
  .github/scripts/constants.js
  .github/scripts/label_missing_related_issue.js
  .github/scripts/label_pr_based_on_title.js
Labels: size/XS

#1439 chore(ci): add condition to check if analytics workflow is running on main repo
  .github/workflows/dispatch_analytics.yml
Labels: area/automation, size/XS

#1441 chore(ci): pin all 3rd party actions
  .github/workflows/closed-issues-message.yml
  .github/workflows/dispatch_analytics.yml
  .github/workflows/label_pr_on_title.yml
  .github/workflows/make-release.yml
  .github/workflows/measure-packages-size.yml
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on-workflows-push-pr.yml
  .github/workflows/on_opened_pr.yml
  .github/workflows/post-release.yml
  .github/workflows/publish_layer.yml
  .github/workflows/record_pr.yml
  .github/workflows/reusable-publish-docs.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  .github/workflows/reusable_export_pr_details.yml
  .github/workflows/reusable_update_layer_arn_docs.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/stale-issues.yml
Labels: area/automation, size/L

#1452 style(maintenance): add `prettier` to the project
  .prettierrc
  package-lock.json
  package.json
Labels: type/dependencies, size/S

#1454 style(commons): apply standardized formatting
  packages/commons/.eslintrc.js
  packages/commons/jest.config.js
  packages/commons/package.json
  packages/commons/src/Utility.ts
  packages/commons/src/config/ConfigService.ts
  packages/commons/src/config/EnvironmentVariablesService.ts
  packages/commons/src/config/index.ts
  packages/commons/src/index.ts
  packages/commons/src/samples/resources/contexts/hello-world.ts
  packages/commons/src/samples/resources/contexts/index.ts
  packages/commons/src/samples/resources/events/index.ts
  packages/commons/src/types/middy.ts
  packages/commons/src/utils/lambda/LambdaInterface.ts
  packages/commons/src/utils/lambda/index.ts
  packages/commons/tests/unit/InvocationLogs.test.ts
  packages/commons/tests/unit/LambdaInterface.test.ts
  packages/commons/tests/unit/Utility.test.ts
  packages/commons/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/commons/tests/utils/InvocationLogs.ts
  packages/commons/tests/utils/cdk-cli.ts
  packages/commons/tests/utils/e2eUtils.ts
Labels: type/dependencies, type/internal, size/XL, type/tests, area/commons

#1457 style(logger): apply standardized formatting
  packages/logger/.eslintrc.js
  packages/logger/jest.config.js
  packages/logger/package.json
  packages/logger/src/Logger.ts
  packages/logger/src/config/ConfigServiceInterface.ts
  packages/logger/src/config/EnvironmentVariablesService.ts
  packages/logger/src/config/index.ts
  packages/logger/src/formatter/LogFormatter.ts
  packages/logger/src/formatter/LogFormatterInterface.ts
  packages/logger/src/formatter/PowertoolLogFormatter.ts
  packages/logger/src/formatter/index.ts
  packages/logger/src/helpers.ts
  packages/logger/src/index.ts
  packages/logger/src/log/LogItem.ts
  packages/logger/src/log/LogItemInterface.ts
  packages/logger/src/log/index.ts
  packages/logger/src/middleware/index.ts
  packages/logger/src/middleware/middy.ts
  packages/logger/src/types/Log.ts
  packages/logger/src/types/Logger.ts
  packages/logger/src/types/formats/PowertoolLog.ts
  packages/logger/src/types/formats/index.ts
  packages/logger/src/types/index.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/childLogger.manual.test.FunctionCode.ts
  packages/logger/tests/e2e/childLogger.manual.test.ts
  packages/logger/tests/e2e/constants.ts
  packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.FunctionCode.ts
  packages/logger/tests/e2e/logEventEnvVarSetting.middy.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.FunctionCode.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/logger/tests/helpers/populateEnvironmentVariables.ts
  packages/logger/tests/helpers/types.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
  packages/logger/tests/unit/helpers.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
Labels: type/dependencies, area/logger, type/internal, size/XXL, type/tests

#1459 style(metrics): apply standardized formatting
  packages/metrics/.eslintrc.js
  packages/metrics/jest.config.js
  packages/metrics/package.json
  packages/metrics/src/Metrics.ts
  packages/metrics/src/MetricsInterface.ts
  packages/metrics/src/config/ConfigServiceInterface.ts
  packages/metrics/src/config/EnvironmentVariablesService.ts
  packages/metrics/src/config/index.ts
  packages/metrics/src/constants.ts
  packages/metrics/src/index.ts
  packages/metrics/src/middleware/index.ts
  packages/metrics/src/middleware/middy.ts
  packages/metrics/src/types/MetricResolution.ts
  packages/metrics/src/types/MetricUnit.ts
  packages/metrics/src/types/Metrics.ts
  packages/metrics/src/types/index.ts
  packages/metrics/tests/e2e/basicFeatures.decorator.test.functionCode.ts
  packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
  packages/metrics/tests/e2e/basicFeatures.manual.test.functionCode.ts
  packages/metrics/tests/e2e/basicFeatures.manual.test.ts
  packages/metrics/tests/e2e/constants.ts
  packages/metrics/tests/helpers/metricsUtils.ts
  packages/metrics/tests/helpers/populateEnvironmentVariables.ts
  packages/metrics/tests/unit/Metrics.test.ts
  packages/metrics/tests/unit/middleware/middy.test.ts
Labels: type/dependencies, area/metrics, type/internal, size/XXL, type/tests

#1458 style(tracer): apply standardized formatting
  packages/tracer/.eslintrc.js
  packages/tracer/jest.config.js
  packages/tracer/package.json
  packages/tracer/src/Tracer.ts
  packages/tracer/src/TracerInterface.ts
  packages/tracer/src/config/ConfigServiceInterface.ts
  packages/tracer/src/config/EnvironmentVariablesService.ts
  packages/tracer/src/config/index.ts
  packages/tracer/src/helpers.ts
  packages/tracer/src/index.ts
  packages/tracer/src/middleware/middy.ts
  packages/tracer/src/provider/ProviderService.ts
  packages/tracer/src/provider/ProviderServiceInterface.ts
  packages/tracer/src/provider/index.ts
  packages/tracer/src/types/Tracer.ts
  packages/tracer/src/types/index.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.functionCode.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
  packages/tracer/tests/e2e/constants.ts
  packages/tracer/tests/helpers/FunctionSegmentNotDefinedError.ts
  packages/tracer/tests/helpers/populateEnvironmentVariables.ts
  packages/tracer/tests/helpers/traceAssertions.ts
  packages/tracer/tests/helpers/traceUtils.types.ts
  packages/tracer/tests/helpers/tracesUtils.ts
  packages/tracer/tests/unit/ProviderService.test.ts
  packages/tracer/tests/unit/Tracer.test.ts
  packages/tracer/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/tracer/tests/unit/helpers.test.ts
  packages/tracer/tests/unit/middy.test.ts
Labels: type/dependencies, area/tracer, type/internal, size/XXL, type/tests

#1460 style(docs): apply standardized formatting
  examples/cdk/.eslintrc.js
  examples/cdk/bin/cdk-app.ts
  examples/cdk/functions/common/constants.ts
  examples/cdk/functions/common/dynamodb-client.ts
  examples/cdk/functions/common/powertools.ts
  examples/cdk/functions/get-all-items.ts
  examples/cdk/functions/get-by-id.ts
  examples/cdk/functions/put-item.ts
  examples/cdk/jest.config.js
  examples/cdk/package.json
  examples/cdk/src/example-stack.ts
Labels: area/documentation, type/dependencies, type/internal, size/L

#1461 style(docs): apply standardized formatting
  examples/sam/.eslintrc.js
  examples/sam/jest.config.js
  examples/sam/package.json
  examples/sam/src/common/constants.ts
  examples/sam/src/common/dynamodb-client.ts
  examples/sam/src/common/powertools.ts
  examples/sam/src/get-all-items.ts
  examples/sam/src/get-by-id.ts
  examples/sam/src/put-item.ts
  examples/sam/tests/sam.test.ts
Labels: area/documentation, type/dependencies, type/internal, size/L

#1442 test(idempotency): add e2e tests for idempotency
  packages/commons/tests/utils/e2eUtils.ts
  packages/idempotency/package.json
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/src/makeFunctionIdempotent.ts
  packages/idempotency/src/types/IdempotencyOptions.ts
  packages/idempotency/tests/e2e/constants.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/helpers/idempotencyUtils.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
Labels: type/dependencies, area/idempotency, size/XL, type/tests

#1464 style(idempotency): apply standardized formatting
  .eslintrc.js
  docs/snippets/.eslintrc.js
  examples/cdk/.eslintrc.js
  examples/sam/.eslintrc.js
  layers/.eslintrc.js
  packages/commons/.eslintrc.js
  packages/commons/tests/utils/e2eUtils.ts
  packages/idempotency/jest.config.js
  packages/idempotency/package.json
  packages/idempotency/src/Exceptions.ts
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/config/ConfigServiceInterface.ts
  packages/idempotency/src/config/EnvironmentVariablesService.ts
  packages/idempotency/src/config/index.ts
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/src/makeFunctionIdempotent.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/src/persistence/BasePersistenceLayerInterface.ts
  packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
  packages/idempotency/src/persistence/IdempotencyRecord.ts
  packages/idempotency/src/persistence/LRUCache.ts
  packages/idempotency/src/persistence/index.ts
  packages/idempotency/src/types/AnyFunction.ts
  packages/idempotency/src/types/BasePersistenceLayer.ts
  packages/idempotency/src/types/DynamoDBPersistence.ts
  packages/idempotency/src/types/IdempotencyOptions.ts
  packages/idempotency/src/types/IdempotencyRecord.ts
  packages/idempotency/src/types/LRUCache.ts
  packages/idempotency/src/types/index.ts
  packages/idempotency/tests/e2e/constants.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/helpers/idempotencyUtils.ts
  packages/idempotency/tests/helpers/populateEnvironmentVariables.ts
  packages/idempotency/tests/unit/IdempotencyConfig.test.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/config/EnvironmentVariableService.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/IdempotencyRecord.test.ts
  packages/idempotency/tests/unit/persistence/LRUCache.test.ts
  packages/logger/.eslintrc.js
  packages/metrics/.eslintrc.js
  packages/parameters/.eslintrc.js
  packages/tracer/.eslintrc.js
  typedoc.js
Labels: area/documentation, type/dependencies, type/internal, area/idempotency, size/XXL, type/tests

#1468 chore(ci): add step to publish docs to S3
  .github/workflows/on_doc_merge.yml
  .github/workflows/publish_layer.yml
  .github/workflows/rebuild-latest-docs.yml
  .github/workflows/reusable-publish-docs.yml
Labels: area/automation, size/M

#1470 chore(docs): fix workflow secrets
  .github/workflows/on_doc_merge.yml
  .github/workflows/reusable-publish-docs.yml
Labels: type/bug, area/automation, size/S

#1473 feat(commons): add `cleanupPowertools` function
  packages/commons/src/middleware/cleanupMiddlewares.ts
  packages/commons/src/middleware/constants.ts
  packages/commons/src/middleware/index.ts
  packages/commons/src/types/middy.ts
  packages/commons/tests/unit/cleanupMiddlewares.test.ts
Labels: size/L, type/feature, type/tests, area/commons
