Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-04, with the labels that each got.

#1394 chore(ci): update lerna to latest version
  .github/workflows/make-release.yml
  package-lock.json
  package.json
  packages/commons/package.json
  packages/idempotency/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/parameters/package.json
  packages/tracer/package.json
Labels: type/internal, size/M

#1387 feat(parameters): stronger types for SSM getParameter
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/ssm/getParameter.ts
  packages/parameters/src/ssm/getParameters.ts
  packages/parameters/src/ssm/getParametersByName.ts
  packages/parameters/src/types/BaseProvider.ts
  packages/parameters/src/types/SSMProvider.ts
  packages/parameters/tests/unit/getParameter.test.ts
  packages/parameters/tests/unit/getParameters.test.ts
Labels: size/L, type/feature

#1396 feat(idempotency): add local cache to `BasePersistenceLayer`
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/src/persistence/IdempotencyRecord.ts
  packages/idempotency/src/persistence/LRUCache.ts
  packages/idempotency/src/types/IdempotencyOptions.ts
  packages/idempotency/src/types/LRUCache.ts
  packages/idempotency/src/types/index.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/LRUCache.test.ts
Labels: size/XL, type/feature

#1399 feat(logger): add `CRITICAL` log level
  packages/logger/src/Logger.ts
  packages/logger/src/types/Log.ts
  packages/logger/src/types/Logger.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/helpers.test.ts
Labels: size/L, type/feature

#1405 chore(ci): phase out `aws-sdk` usage
  docs/snippets/package.json
  examples/cdk/functions/get-all-items.ts
  examples/cdk/functions/get-by-id.ts
  examples/cdk/functions/put-item.ts
  examples/cdk/package-lock.json
  examples/cdk/package.json
  examples/sam/src/put-item.ts
  layers/tests/unit/layer-publisher.test.ts
  package-lock.json
  package.json
  packages/commons/package.json
  packages/commons/tests/utils/e2eUtils.ts
  packages/tracer/package.json
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.functionCode.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
  packages/tracer/tests/helpers/traceAssertions.ts
  packages/tracer/tests/helpers/traceUtils.types.ts
  packages/tracer/tests/helpers/tracesUtils.ts
  packages/tracer/tests/unit/Tracer.test.ts
Labels: type/internal, size/L

#1408 build(deps): bump xml2js from 0.4.19 to 0.5.0
  package-lock.json
Labels: size/XS

#1411 feat(parameters): add adaptive types to SecretsProvider
  packages/parameters/src/secrets/SecretsProvider.ts
  packages/parameters/src/secrets/getSecret.ts
  packages/parameters/src/types/SecretsProvider.ts
  packages/parameters/tests/unit/getSecret.test.ts
Labels: area/parameters, size/L, type/feature

#1413 chore(parameters): update generics names in SSMProvider
  package-lock.json
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/ssm/getParameter.ts
  packages/parameters/src/ssm/getParameters.ts
  packages/parameters/src/ssm/getParametersByName.ts
  packages/parameters/src/types/SSMProvider.ts
  packages/parameters/tests/unit/SSMProvider.test.ts
  packages/parameters/tests/unit/getParametersByName.test.ts
Labels: type/internal, size/L

#1414 refactor(metrics): unit tests for Metrics are written to follow similar convention as Logger/Tracer
  packages/metrics/src/Metrics.ts
  packages/metrics/src/constants.ts
  packages/metrics/tests/helpers/metricsUtils.ts
  packages/metrics/tests/unit/Metrics.test.ts
Labels: size/XXL, type/feature

#1418 chore(ci): add workflow to dispatch analytics fetching
  .github/workflows/dispatch_analytics.yml
Labels: type/internal, size/M

#1420 chore(docs): add customer references section
  README.md
  docs/index.md
  docs/media/logos/globaldatanet.png
  docs/media/logos/hashnode.png
  docs/media/logos/perfect-post.png
  docs/media/logos/sennder.png
  docs/media/logos/trek10.jpg
  docs/we_made_this.md
  mkdocs.yml
  packages/commons/README.md
  packages/idempotency/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/tracer/README.md
Labels: type/internal, size/L

#1416 feat(idempotency): implement IdempotencyHandler
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/src/makeFunctionIdempotent.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
Labels: size/L, type/feature

#1423 chore(docs): fix warning format in metrics documentation
  docs/core/metrics.md
Labels: area/documentation, type/internal, size/XS
