Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-01, with the labels that each got.

#1208 chore(docs): update year in docs
  mkdocs.yml
Labels: type/internal, size/XS

#1206 feat(parameters): SecretsProvider support
  package-lock.json
  packages/parameters/package.json
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/secrets/SecretsProvider.ts
  packages/parameters/src/secrets/getSecret.ts
  packages/parameters/src/secrets/index.ts
  packages/parameters/src/types/BaseProvider.ts
  packages/parameters/src/types/SecretsProvider.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tests/unit/SecretsProvider.test.ts
  packages/parameters/tests/unit/getSecret.test.ts
Labels: area/parameters, size/L, type/feature

#1214 refactor: types in BaseProvider + added getMultiple alias to SecretsProvider
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/secrets/SecretsProvider.ts
Labels: area/parameters, size/S, type/feature

#1187 feat(parameters): SSMProvider support
  package-lock.json
  packages/parameters/package.json
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/ssm/getParameter.ts
  packages/parameters/src/ssm/getParameters.ts
  packages/parameters/src/ssm/getParametersByName.ts
  packages/parameters/src/ssm/index.ts
  packages/parameters/src/types/SSMProvider.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tests/unit/SSMProvider.test.ts
  packages/parameters/tests/unit/getParameter.test.ts
  packages/parameters/tests/unit/getParameters.test.ts
  packages/parameters/tests/unit/getParametersByName.test.ts
Labels: area/parameters, size/XXL, type/feature

#1200 feat(parameters): AppConfigProvider
  package-lock.json
  packages/parameters/package.json
  packages/parameters/src/appconfig/AppConfigProvider.ts
  packages/parameters/src/appconfig/getAppConfig.ts
  packages/parameters/src/appconfig/index.ts
  packages/parameters/src/types/AppConfigProvider.ts
  packages/parameters/tests/unit/AppConfigProvider.test.ts
  packages/parameters/tests/unit/getAppConfig.test.ts
Labels: area/parameters, size/L, type/feature

#1202 feat(parameters): DynamoDBProvider support
  package-lock.json
  packages/parameters/package.json
  packages/parameters/src/dynamodb/DynamoDBProvider.ts
  packages/parameters/src/dynamodb/index.ts
  packages/parameters/src/types/DynamoDBProvider.ts
  packages/parameters/tests/unit/DynamoDBProvider.test.ts
Labels: area/parameters, size/XL, type/feature

#1217 chore(docs): bumped mkdocs-material to latest + small tweaks
  docs/requirements.txt
  mkdocs.yml
Labels: size/S

#1215 docs(parameters): main docs for the utility
  docs/snippets/parameters/adjustingCacheTTL.ts
  docs/snippets/parameters/appConfigProvider.ts
  docs/snippets/parameters/appConfigProviderCustomClient.ts
  docs/snippets/parameters/clientConfig.ts
  docs/snippets/parameters/dynamoDBProvider.ts
  docs/snippets/parameters/dynamoDBProviderCustomClient.ts
  docs/snippets/parameters/dynamoDBProviderCustomizeTable.ts
  docs/snippets/parameters/dynamoDBProviderLocal.ts
  docs/snippets/parameters/dynamoDBProviderMultiple.ts
  docs/snippets/parameters/forceFetch.ts
  docs/snippets/parameters/getAppConfig.ts
  docs/snippets/parameters/getParameter.ts
  docs/snippets/parameters/getParameters.ts
  docs/snippets/parameters/getParametersByName.ts
  docs/snippets/parameters/getParametersByNameGracefulErrorHandling.ts
  docs/snippets/parameters/getSecret.ts
  docs/snippets/parameters/sdkOptions.ts
  docs/snippets/parameters/secretsProvider.ts
  docs/snippets/parameters/secretsProviderCustomClient.ts
  docs/snippets/parameters/ssmProvider.ts
  docs/snippets/parameters/ssmProviderCustomClient.ts
  docs/snippets/parameters/ssmProviderDecryptAndRecursive.ts
  docs/snippets/parameters/transform.ts
  docs/snippets/parameters/transformAuto.ts
  docs/snippets/parameters/transformPartialFailures.ts
  docs/snippets/parameters/transformProvider.ts
  docs/snippets/parameters/tsconfig.json
  docs/utilities/parameters.md
Labels: area/documentation, size/XL

#1223 chore(parameters): revisit utility types
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/ssm/getParametersByName.ts
  packages/parameters/src/ssm/index.ts
  packages/parameters/src/types/AppConfigProvider.ts
  packages/parameters/src/types/BaseProvider.ts
  packages/parameters/src/types/SSMProvider.ts
  packages/parameters/src/types/index.ts
  packages/parameters/tests/unit/AppConfigProvider.test.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tests/unit/getParametersByName.test.ts
Labels: type/internal, size/M

#1229 docs(tracer): extract Tracer code snippets in separate files #1219
  docs/core/tracer.md
  docs/snippets/tracer/accessRootTraceId.ts
  docs/snippets/tracer/basicUsage.ts
  docs/snippets/tracer/captureAWS.ts
  docs/snippets/tracer/captureAWSAll.ts
  docs/snippets/tracer/captureAWSv3.ts
  docs/snippets/tracer/captureHTTP.ts
  docs/snippets/tracer/captureMethodDecorator.ts
  docs/snippets/tracer/captureMethodManual.ts
  docs/snippets/tracer/decorator.ts
  docs/snippets/tracer/disableCaptureResponseHandler.ts
  docs/snippets/tracer/disableCaptureResponseMethod.ts
  docs/snippets/tracer/disableCaptureResponseMiddy.ts
  docs/snippets/tracer/escapeHatch.ts
  docs/snippets/tracer/manual.ts
  docs/snippets/tracer/middy.ts
  docs/snippets/tracer/putAnnotation.ts
  docs/snippets/tracer/putMetadata.ts
  docs/snippets/tracer/sam.ts
Labels: area/documentation, size/L

#1230 docs(logger): extract Logger code snippets in separate files
  docs/core/logger.md
  docs/snippets/logger/appendKeys.ts
  docs/snippets/logger/basicUsage.ts
  docs/snippets/logger/bringYourOwnFormatterClass.ts
  docs/snippets/logger/bringYourOwnFormatterHandler.ts
  docs/snippets/logger/clearStateDecorator.ts
  docs/snippets/logger/clearStateMiddy.ts
  docs/snippets/logger/createChild.ts
  docs/snippets/logger/decorator.ts
  docs/snippets/logger/eventDecorator.ts
  docs/snippets/logger/eventMiddy.ts
  docs/snippets/logger/extraData.ts
  docs/snippets/logger/logError.ts
  docs/snippets/logger/logSampling.ts
  docs/snippets/logger/manual.ts
  docs/snippets/logger/middy.ts
  docs/snippets/logger/sam.ts
  docs/snippets/logger/unitTesting.ts
Labels: area/documentation, size/XL

#1225 refactor(all): add middy-like types to commons
  packages/commons/src/index.ts
  packages/commons/src/types/middy.ts
  packages/logger/src/middleware/middy.ts
  packages/metrics/src/middleware/middy.ts
  packages/tracer/src/middleware/middy.ts
Labels: size/M, type/feature

#1232 chore(layers): bump hardcoded cdk version in `publish_layer.yaml`
  .github/workflows/publish_layer.yaml
Labels: size/XS

#1234 chore(layers): bump hardcoded version in `reusable_deploy_layer_stack.yml`
  .github/workflows/reusable_deploy_layer_stack.yml
Labels: type/internal, size/XS

#1235 docs: update layer version to 7
  docs/index.md
Labels: size/M

#1237 docs: remove Node.js 12 deprecation notice from docs
  docs/overrides/main.html
Labels: area/documentation, size/XS

#1239 fix(parameters): Tokenize attribute names in `DynamoDBProvider`
  docs/utilities/parameters.md
  package-lock.json
  packages/parameters/package.json
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/dynamodb/DynamoDBProvider.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tests/unit/DynamoDBProvider.test.ts
Labels: type/bug, size/M

#1249 chore(internal): add @middy/core license to proejct third-party licenses
  LICENSE-THIRD-PARTY
Labels: type/internal, size/S

#1247 docs: correct link to Powertools for Java
  docs/index.md
Labels: area/documentation, size/XS

#1251 chore(docs): add `docs/snippets` to npm workspace
  docs/Dockerfile
  docs/requirements.txt
  docs/snippets/package.json
  mkdocs.yml
  package-lock.json
  package.json
Labels: type/internal, size/M

#1254 fix(docs): logger bringYourOwnFormatter snippet
  docs/snippets/logger/bringYourOwnFormatterClass.ts
Labels: type/bug, size/M
