Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-06, with the labels that each got.

#1478 chore(docs): fix setup steps in contributing doc
  .devcontainer/devcontainer.json
  .gitpod.yml
  CONTRIBUTING.md
  README.md
  packages/commons/README.md
  packages/idempotency/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/tracer/README.md
Labels: type/internal, size/L

#1483 feat(idempotency): add package exports
  packages/idempotency/package.json
  packages/idempotency/src/index.ts
  packages/idempotency/src/persistence/index.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/unit/IdempotencyConfig.test.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/IdempotencyRecord.test.ts
Labels: type/dependencies, area/idempotency, size/L, type/feature, type/tests

#1474 feat(idempotency): `makeHandlerIdempotent` middy middleware
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/config/ConfigServiceInterface.ts
  packages/idempotency/src/config/EnvironmentVariablesService.ts
  packages/idempotency/src/constants.ts
  packages/idempotency/src/makeFunctionIdempotent.ts
  packages/idempotency/src/middleware/index.ts
  packages/idempotency/src/middleware/makeHandlerIdempotent.ts
  packages/idempotency/src/types/AnyFunction.ts
  packages/idempotency/tests/helpers/idempotencyUtils.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
Labels: area/idempotency, size/XL, type/feature, type/tests

#1487 feat(idempotency): idempotency middleware & types exports
  packages/idempotency/package.json
  packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
Labels: type/dependencies, area/idempotency, size/S, type/feature

#1489 chore(tests): restore parameter in e2eUtils
  packages/commons/tests/utils/e2eUtils.ts
Labels: size/XS, type/tests

#1485 docs(idempotency): API docs for idempotency
  package-lock.json
  package.json
  packages/commons/package.json
  packages/commons/typedoc.json
  packages/idempotency/README.md
  packages/idempotency/package.json
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/src/makeFunctionIdempotent.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
  packages/idempotency/src/persistence/IdempotencyRecord.ts
  packages/idempotency/src/types/DynamoDBPersistence.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
  packages/idempotency/typedoc.json
  packages/logger/package.json
  packages/logger/typedoc.json
  packages/metrics/package.json
  packages/metrics/typedoc.json
  packages/parameters/package.json
  packages/parameters/src/docs.ts
  packages/parameters/typedoc.json
  packages/tracer/typedoc.json
  tsconfig.json
  typedoc.base.json
  typedoc.js
  typedoc.json
Labels: type/dependencies, type/internal, area/idempotency, area/parameters, size/L, type/tests

#1497 build(internal): bump `@aws-sdk/client-*`
  package-lock.json
Labels: type/dependencies, size/XS

#1495 chore(logger): correct homepage link in logger package.
  packages/logger/package.json
Labels: type/dependencies, size/XS

#1504 chore(maintenance): cleaned up `package.json` files
  .github/actions/cached-node-modules/action.yml
  .github/scripts/release_patch_package_json.js
  .github/workflows/make-release.yml
  README.md
  docs/snippets/package.json
  examples/cdk/package.json
  examples/sam/package.json
  examples/sam/template.yaml
  layers/package.json
  lerna.json
  package-bundler.sh
  package-lock.json
  package.json
  packages/commons/package.json
  packages/idempotency/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/parameters/package.json
  packages/tracer/package.json
Labels: area/documentation, type/dependencies, area/automation, type/internal, size/L

#1505 chore(docs): added back s3 bucket to workflow
  .github/workflows/reusable-publish-docs.yml
Labels: area/automation, size/XS

#1506 chore(ci): update post release workflow
  .github/scripts/label_related_issue.js
  .github/scripts/post_release.js
Labels: area/automation, size/L

#1507 fix(idempotency): skip persistence for optional idempotency key
  package.json
  packages/commons/tests/utils/e2eUtils.ts
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/middleware/makeHandlerIdempotent.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.manual.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/e2e/asyncHandler.decorator.test.ts
  packages/tracer/tests/helpers/tracesUtils.ts
Labels: type/bug, area/idempotency, size/L, type/tests

#1521 fix(docs): upload versions.json
  .github/workflows/reusable-publish-docs.yml
Labels: type/bug

#1522 fix(docs): aliases in versions.json
  .github/workflows/reusable-publish-docs.yml
Labels: type/bug

#1543 chore: update `CODEOWNERS` file
  .github/CODEOWNERS
Labels: type/internal, size/XS

#1541 chore(ci): bump `lerna` & add provenance config
  .github/workflows/make-release.yml
  package-lock.json
  package.json
Labels: type/dependencies, area/automation, size/S

#1540 fix(idempotency): pass lambda context remaining time to save inprogress
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
Labels: type/bug, area/idempotency, size/L, type/tests

#1528 feat(parameters): review types and exports
  packages/commons/src/index.ts
  packages/commons/src/types/utils.ts
  packages/commons/tests/unit/utils.test.ts
  packages/parameters/package.json
  packages/parameters/src/BaseProvider.ts
  packages/parameters/src/appconfig/AppConfigProvider.ts
  packages/parameters/src/appconfig/getAppConfig.ts
  packages/parameters/src/base/BaseProvider.ts
  packages/parameters/src/base/DefaultProviders.ts
  packages/parameters/src/base/ExpirableValue.ts
  packages/parameters/src/base/GetMultipleOptions.ts
  packages/parameters/src/base/GetOptions.ts
  packages/parameters/src/base/index.ts
  packages/parameters/src/base/transformValue.ts
  packages/parameters/src/constants.ts
  packages/parameters/src/dynamodb/DynamoDBProvider.ts
  packages/parameters/src/errors.ts
  packages/parameters/src/index.ts
  packages/parameters/src/secrets/SecretsProvider.ts
  packages/parameters/src/secrets/getSecret.ts
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/ssm/getParameter.ts
  packages/parameters/src/ssm/getParameters.ts
  packages/parameters/src/types/AppConfigProvider.ts
  packages/parameters/src/types/BaseProvider.ts
  packages/parameters/src/types/DynamoDBProvider.ts
  packages/parameters/src/types/SSMProvider.ts
  packages/parameters/src/types/SecretsProvider.ts
  packages/parameters/src/types/index.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.ts
  packages/parameters/tests/e2e/dynamoDBProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/secretsProvider.class.test.functionCode.ts
  packages/parameters/tests/e2e/secretsProvider.class.test.ts
  packages/parameters/tests/e2e/ssmProvider.class.test.functionCode.ts
  packages/parameters/tests/unit/AppConfigProvider.test.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tests/unit/SSMProvider.test.ts
  packages/parameters/tests/unit/getAppConfig.test.ts
  packages/parameters/tests/unit/getParameter.test.ts
  packages/parameters/tests/unit/getParameters.test.ts
  packages/parameters/tests/unit/getParametersByName.test.ts
  packages/parameters/tests/unit/getSecret.test.ts
  packages/parameters/typedoc.json
Labels: type/dependencies, area/parameters, size/XXL, type/feature, type/tests, area/commons

#1545 feat(tracer): close & restore segments when other middlewares return
  packages/tracer/src/middleware/middy.ts
  packages/tracer/tests/unit/middy.test.ts
Labels: area/tracer, size/M, type/feature, type/tests

#1549 fix(docs/ci): change how versions and aliases are inserted into versions.json
  .github/workflows/reusable-publish-docs.yml
Labels: type/bug, area/automation, size/XS

#1513 chore(ci): remove GH pages
  .github/workflows/reusable-publish-docs.yml
Labels: area/automation, size/S

#1547 docs(parameters): refresh `README` for utility with usage examples
  docs/snippets/parameters/getParametersByName.ts
  docs/snippets/parameters/getParametersByNameGracefulErrorHandling.ts
  docs/utilities/parameters.md
  packages/parameters/README.md
Labels: area/documentation, size/L

#1531 chore: update roadmap
  MAINTAINERS.md
  docs/roadmap.md
Labels: area/documentation, type/internal, size/M

#1548 fix(metrics): flush metrics when data points array reaches max size
  packages/metrics/src/Metrics.ts
  packages/metrics/src/constants.ts
  packages/metrics/tests/unit/Metrics.test.ts
Labels: type/bug, area/metrics, size/M, type/tests

#1552 feat(idempotency): preserve original error when wrapping into `IdempotencyPersistenceLayerError`
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/errors.ts
  packages/idempotency/src/index.ts
  packages/idempotency/src/middleware/makeHandlerIdempotent.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
  packages/idempotency/src/persistence/IdempotencyRecord.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/makeFunctionIdempotent.test.ts
  packages/idempotency/tests/unit/makeHandlerIdempotent.test.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/IdempotencyRecord.test.ts
Labels: area/idempotency, size/M, type/feature, type/tests

#1561 chore(tests): upgrade `@aws-sdk/*` pacakges
  docs/snippets/package.json
  examples/cdk/package.json
  examples/sam/package.json
  package-lock.json
  packages/commons/package.json
  packages/idempotency/package.json
  packages/metrics/package.json
  packages/parameters/package.json
  packages/parameters/tests/unit/AppConfigProvider.test.ts
  packages/parameters/tests/unit/getAppConfig.test.ts
  packages/tracer/package.json
Labels: area/documentation, type/dependencies, size/M, type/tests

#1563 chore(docs): add certible + logo
  docs/index.md
  docs/media/logos/certible.svg
  packages/commons/README.md
  packages/idempotency/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/tracer/README.md
Labels: area/documentation, type/internal, size/XS

#1554 chore(idempotency): remove decorators
  packages/idempotency/README.md
  packages/idempotency/src/idempotentDecorator.ts
  packages/idempotency/src/index.ts
  packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
  packages/idempotency/src/persistence/IdempotencyRecord.ts
  packages/idempotency/src/types/DynamoDBPersistence.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/idempotencyDecorator.test.ts
  packages/idempotency/tests/unit/idempotentDecorator.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
  packages/idempotency/typedoc.json
Labels: type/internal, area/idempotency, size/XXL, type/tests

#1565 docs(parameters): release tasks + add docs on bring your own provider
  .github/scripts/release_patch_package_json.js
  README.md
  docs/snippets/package.json
  docs/snippets/parameters/customProviderVault.ts
  docs/snippets/parameters/customProviderVaultTypes.ts
  docs/snippets/parameters/customProviderVaultUsage.ts
  docs/utilities/parameters.md
  package-lock.json
  packages/commons/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/tracer/README.md
Labels: area/documentation, type/dependencies, area/automation, type/internal, size/L
