Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2023-11, with the labels that each got.

#1778 docs(maintenance): add clarification about async decorators
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/utilities/idempotency.md
Labels: area/documentation, size/M

#1780 fix(metrics): deduplicate dimensions when serialising
  .gitignore
  packages/metrics/src/Metrics.ts
  packages/metrics/tests/unit/Metrics.test.ts
Labels: type/bug, area/metrics, size/M, type/tests

#1782 chore(maintenance): improve Gitpod config
  .gitpod.Dockerfile
  .gitpod.yml
Labels: type/internal, size/S

#1775 chore(logger): set default UTC timezone
  packages/logger/src/Logger.ts
  packages/logger/src/config/EnvironmentVariablesService.ts
  packages/logger/src/formatter/LogFormatter.ts
  packages/logger/src/types/Log.ts
  packages/logger/tests/unit/EnvironmentVariablesService.test.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/tracer/tests/helpers/tracesUtils.ts
Labels: area/logger, size/M

#1786 feat(metrics): log directly to stdout
  layers/tests/e2e/layerPublisher.test.ts
  packages/commons/src/config/ConfigService.ts
  packages/commons/src/config/EnvironmentVariablesService.ts
  packages/commons/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/logger/src/config/EnvironmentVariablesService.ts
  packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/metrics/src/Metrics.ts
  packages/metrics/src/config/ConfigServiceInterface.ts
  packages/metrics/tests/unit/Metrics.test.ts
  packages/metrics/tests/unit/middleware/middy.test.ts
Labels: area/logger, area/metrics, size/XL, type/feature, area/commons

#1790 feat(maintenance): add support for nodejs20.x runtime
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/actions/cached-node-modules/action.yml
  .github/workflows/make-release.yml
  .github/workflows/make-v2-release.yml
  .github/workflows/publish_layer.yml
  .github/workflows/reusable-publish-docs.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  .github/workflows/run-e2e-tests.yml
  .nvmrc
  docs/contributing/setup.md
  docs/contributing/testing.md
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/snippets/batch/templates/sam/dynamodb.yaml
  docs/snippets/batch/templates/sam/kinesis.yaml
  docs/snippets/batch/templates/sam/sqs.yaml
  docs/snippets/idempotency/templates/tableCdk.ts
  docs/snippets/idempotency/templates/tableSam.yaml
  docs/snippets/idempotency/templates/tableTerraform.tf
  docs/utilities/idempotency.md
  docs/utilities/parameters.md
  examples/cdk/package.json
  examples/cdk/src/example-stack.ts
  examples/sam/template.yaml
  layers/package.json
  layers/src/layer-publisher-stack.ts
  layers/tests/unit/layer-publisher.test.ts
  package-lock.json
  packages/batch/package.json
  packages/batch/tests/helpers/populateEnvironmentVariables.ts
  packages/commons/src/version.ts
  packages/idempotency/package.json
  packages/idempotency/tests/e2e/idempotentDecorator.test.ts
  packages/logger/package.json
  packages/logger/tests/unit/formatter/PowertoolLogFormatter.test.ts
  packages/metrics/package.json
  packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
  packages/metrics/tests/e2e/basicFeatures.manual.test.ts
  packages/metrics/tests/helpers/metricsUtils.ts
  packages/parameters/package.json
  packages/testing/package.json
  packages/testing/src/constants.ts
  packages/tracer/package.json
Labels: type/dependencies, area/automation, size/L, type/feature

#1795 feat(logger): add support for `AWS_LAMBDA_LOG_LEVEL` and `POWERTOOLS_LOG_LEVEL`
  docs/core/logger.md
  docs/core/metrics.md
  docs/index.md
  docs/snippets/batch/templates/sam/dynamodb.yaml
  docs/snippets/batch/templates/sam/sqs.yaml
  examples/cdk/src/example-stack.ts
  examples/sam/template.yaml
  packages/logger/src/Logger.ts
  packages/logger/src/config/ConfigServiceInterface.ts
  packages/logger/src/config/EnvironmentVariablesService.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/constants.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/logger/tests/helpers/populateEnvironmentVariables.ts
  packages/logger/tests/unit/Logger.test.ts
  packages/logger/tests/unit/config/EnvironmentVariablesService.test.ts
  packages/logger/tests/unit/helpers.test.ts
  packages/logger/tests/unit/middleware/middy.test.ts
Labels: area/documentation, area/logger, size/L, type/feature, type/tests

#1797 chore(ci): Add OSSF Scorecard Workflow
  .github/workflows/ossf_scorecard.yml
Labels: area/automation, need-issue, size/M

#1800 chore(ci): Fix pinned dependencies
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/reusable-publish-docs.yml
  .gitpod.Dockerfile
  docs/Dockerfile
  docs/docker-requirements.txt
  docs/requirements.out
Labels: area/documentation, area/automation, type/internal, size/XL

#1802 chore(maintenance): drop support for Node.js 14
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .github/workflows/run-e2e-tests.yml
  layers/src/canary-stack.ts
  layers/src/layer-publisher-stack.ts
  layers/tests/e2e/constants.ts
  layers/tests/unit/layer-publisher.test.ts
  package-lock.json
  package.json
  packages/commons/src/awsSdk/userAgentMiddleware.ts
  packages/commons/src/types/middy.ts
  packages/idempotency/tests/e2e/constants.ts
  packages/logger/src/Logger.ts
  packages/logger/src/formatter/LogFormatter.ts
  packages/logger/tests/e2e/constants.ts
  packages/metrics/tests/e2e/constants.ts
  packages/parameters/src/appconfig/AppConfigProvider.ts
  packages/parameters/src/appconfig/getAppConfig.ts
  packages/parameters/src/dynamodb/DynamoDBProvider.ts
  packages/parameters/src/secrets/SecretsProvider.ts
  packages/parameters/src/secrets/getSecret.ts
  packages/parameters/src/ssm/SSMProvider.ts
  packages/parameters/src/ssm/getParameter.ts
  packages/parameters/src/ssm/getParameters.ts
  packages/parameters/src/types/AppConfigProvider.ts
  packages/parameters/src/types/DynamoDBProvider.ts
  packages/parameters/src/types/SSMProvider.ts
  packages/parameters/src/types/SecretsProvider.ts
  packages/parameters/tests/e2e/constants.ts
  packages/parameters/tests/helpers/sdkMiddlewareRequestCounter.ts
  packages/parameters/tests/unit/SSMProvider.test.ts
  packages/parameters/tests/unit/getParameters.test.ts
  packages/testing/src/constants.ts
  packages/tracer/tests/e2e/constants.ts
  packages/tracer/tests/unit/Tracer.test.ts
  tsconfig.json
Labels: type/dependencies, area/logger, area/automation, type/internal, area/parameters, size/L, type/tests, area/layers, area/commons

#1801 chore(ci): sets base permissions on all workflows
  .github/workflows/closed-issues-message.yml
  .github/workflows/label_pr_on_title.yml
  .github/workflows/make-release.yml
  .github/workflows/make-v2-release.yml
  .github/workflows/measure-packages-size.yml
  .github/workflows/on-doc-v2-merge.yml
  .github/workflows/on-merge-to-main.yml
  .github/workflows/on-workflows-push-pr.yml
  .github/workflows/on_doc_merge.yml
  .github/workflows/on_opened_pr.yml
  .github/workflows/post-release.yml
  .github/workflows/pr-run-linting-check-and-unit-tests.yml
  .github/workflows/rebuild-latest-docs.yml
  .github/workflows/record_pr.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  .github/workflows/reusable_export_pr_details.yml
  .github/workflows/run-e2e-tests.yml
  .github/workflows/stale-issues.yml
Labels: area/automation, size/M

#1805 chore(docs): fix layer version in CDK example
  examples/cdk/src/example-stack.ts
Labels: area/documentation, size/XS
