Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2024-04, with the labels that each got.

#2301 chore(docs): fix middy v4 version support
  docs/core/metrics.md
  docs/index.md
  docs/utilities/idempotency.md
Labels: area/documentation, size/XS

#2289 chore(maintenance): make jmespath utility public
  docs/utilities/jmespath.md
  packages/jmespath/package.json
Labels: area/documentation, type/dependencies, size/XS

#2311 fix(idempotency): return correct value from in-memory cache
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/tests/e2e/makeIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
Labels: type/bug, area/idempotency, size/M, type/tests

#1835 docs(parser): add docs for parser utility
  docs/index.md
  docs/snippets/package.json
  docs/snippets/parser/decorator.ts
  docs/snippets/parser/envelopeDecorator.ts
  docs/snippets/parser/envelopeMiddy.ts
  docs/snippets/parser/examplePayload.json
  docs/snippets/parser/extend.ts
  docs/snippets/parser/manual.ts
  docs/snippets/parser/manualSafeParse.ts
  docs/snippets/parser/middy.ts
  docs/snippets/parser/refine.ts
  docs/snippets/parser/safeParseDecorator.ts
  docs/snippets/parser/safeParseMiddy.ts
  docs/snippets/parser/schema.ts
  docs/snippets/parser/types.ts
  docs/snippets/tsconfig.json
  docs/utilities/parser.md
  mkdocs.yml
  package-lock.json
  packages/parser/src/schemas/cloudformation-custom-resource.ts
Labels: area/documentation, type/dependencies, area/automation, status/on-hold, type/internal, size/XL, type/tests, area/parser

#2323 chore(maintenance): document process to add a new region to layers
  docs/maintainers.md
Labels: area/documentation, type/internal, size/XS

#2320 chore(docs): update batch docs highlight & links
  docs/snippets/batch/gettingStartedAsync.ts
  docs/utilities/batch.md
  packages/batch/README.md
Labels: area/documentation, type/internal, size/M

#2330 chore(ci): add monthly roadmap reminder central action
  .github/workflows/on_schedule_monthly_roadmap_reminder.yml
Labels: area/automation, size/S

#2328 chore(docs): streamline docs homepage
  docs/index.md
  mkdocs.yml
Labels: area/documentation, size/XL

#2322 chore(maintenance): update release flow diagram
  docs/maintainers.md
Labels: area/documentation, type/internal, size/M

#2339 feat(parser): add parse error and remove all traces of ZodError
  packages/parser/src/envelopes/apigw.ts
  packages/parser/src/envelopes/apigwv2.ts
  packages/parser/src/envelopes/cloudwatch.ts
  packages/parser/src/envelopes/dynamodb.ts
  packages/parser/src/envelopes/envelope.ts
  packages/parser/src/envelopes/event-bridge.ts
  packages/parser/src/envelopes/kafka.ts
  packages/parser/src/envelopes/kinesis-firehose.ts
  packages/parser/src/envelopes/kinesis.ts
  packages/parser/src/envelopes/lambda.ts
  packages/parser/src/envelopes/sns.ts
  packages/parser/src/envelopes/sqs.ts
  packages/parser/src/envelopes/vpc-lattice.ts
  packages/parser/src/envelopes/vpc-latticev2.ts
  packages/parser/src/errors.ts
  packages/parser/src/index.ts
  packages/parser/src/parser.ts
  packages/parser/tests/unit/envelope.test.ts
  packages/parser/tests/unit/envelopes/apigwt.test.ts
  packages/parser/tests/unit/envelopes/cloudwatch.test.ts
  packages/parser/tests/unit/envelopes/dynamodb.test.ts
  packages/parser/tests/unit/envelopes/eventbridge.test.ts
  packages/parser/tests/unit/envelopes/kinesis.test.ts
  packages/parser/tests/unit/envelopes/sns.test.ts
  packages/parser/tests/unit/envelopes/sqs.test.ts
  packages/parser/tests/unit/parser.decorator.test.ts
Labels: size/L, type/feature, type/tests, area/parser

#2362 chore(parser): add DeadLetterQueueSourceArn attribute
  packages/parser/src/schemas/sqs.ts
  packages/parser/tests/events/sqsEvent.json
Labels: size/XS, type/tests, area/parser

#2364 feat(idempotency): add custom JMESPath functions
  .github/actions/cached-node-modules/action.yml
  .husky/pre-push
  docs/snippets/idempotency/makeIdempotentJmes.ts
  docs/utilities/idempotency.md
  layers/src/layer-publisher-stack.ts
  package-lock.json
  packages/idempotency/README.md
  packages/idempotency/package.json
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/tests/e2e/makeIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeIdempotent.test.ts
Labels: area/documentation, type/dependencies, area/automation, type/internal, area/idempotency, size/L, type/feature, type/tests, area/layers

#2367 refactor(jmespath): rename jmespath parsing options type
  package-lock.json
  package.json
  packages/idempotency/src/IdempotencyConfig.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/jmespath/src/ParsedResult.ts
  packages/jmespath/src/TreeInterpreter.ts
  packages/jmespath/src/envelopes.ts
  packages/jmespath/src/search.ts
  packages/jmespath/src/types.ts
Labels: area/documentation, type/dependencies, area/automation, type/internal, area/idempotency, size/M, type/tests, type/enhancement, area/layers

#2382 chore(parser): add parser to release steps
  .github/actions/cached-node-modules/action.yml
  .github/scripts/release_patch_package_json.js
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  lerna.json
  packages/parser/README.md
  packages/parser/package.json
Labels: type/dependencies, area/automation, type/internal, size/M

#2384 fix(jmespath): refactor custom function introspection to work with minification
  packages/jmespath/src/Functions.ts
  packages/jmespath/tests/unit/index.test.ts
Labels: type/bug, size/M

#2370 test(maintenance): add ESM output to e2e test
  .github/workflows/run-e2e-tests.yml
  docs/index.md
  layers/src/layer-publisher-stack.ts
  layers/tests/e2e/layerPublisher.test.ts
  packages/idempotency/tests/e2e/idempotentDecorator.test.ts
  packages/logger/tests/e2e/basicFeatures.middy.test.ts
  packages/logger/tests/e2e/sampleRate.decorator.test.ts
  packages/metrics/tests/e2e/basicFeatures.decorators.test.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.ts
  packages/parameters/tests/e2e/secretsProvider.class.test.ts
  packages/testing/src/resources/TestNodejsFunction.ts
  packages/testing/src/types.ts
  packages/tracer/tests/e2e/allFeatures.decorator.test.ts
  packages/tracer/tests/e2e/allFeatures.middy.test.ts
  packages/tracer/tests/helpers/resources.ts
Labels: area/documentation, area/automation, size/L, type/tests, area/layers

#2419 chore(maintenance): update labels in automation
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_improvements.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/boring-cyborg.yml
  .github/release-drafter.yml
  .github/scripts/constants.js
  .github/scripts/label_pr_based_on_title.js
  .github/scripts/label_related_issue.js
  .github/workflows/stale-issues.yml
  docs/maintainers.md
Labels: size/L, area/documentation, area/automation, type/internal

#2429 fix(parser): set etag optional for delete object notifications
  packages/parser/src/schemas/s3.ts
  packages/parser/tests/events/s3EventBridgeNotificationObjectDeletedEvent.json
Labels: bug, size/XS, tests, parser

#2430 fix(parser): lambda function url cognitoIdentity and principalOrgId nullable
  packages/parser/src/schemas/apigwv2.ts
  packages/parser/tests/unit/schema/lambda.test.ts
Labels: bug, size/S, tests, parser

#2434 chore(maintenance): add markdownlint
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  .markdownlint.yaml
  .markdownlintignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  MAINTAINERS.md
  README.md
  SECURITY.md
  docs/.markdownlint.yaml
  docs/contributing/conventions.md
  docs/contributing/getting_started.md
  docs/contributing/setup.md
  docs/contributing/testing.md
  docs/core/logger.md
  docs/core/metrics.md
  docs/core/tracer.md
  docs/index.md
  docs/maintainers.md
  docs/roadmap.md
  docs/upgrade.md
  docs/utilities/batch.md
  docs/utilities/idempotency.md
  docs/utilities/jmespath.md
  docs/utilities/parameters.md
  docs/utilities/parser.md
  docs/we_made_this.md
  layers/README.md
  package-lock.json
  package.json
Labels: documentation, dependencies, automation, internal, size/XL

#2435 chore(maintenance): revamp PR & issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_improvements.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/rfc.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: internal, size/M
