Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2024-03, with the labels that each got.

#2161 chore(docs): mark `docs/snippets` package as private
  .github/workflows/make-version.yml
  docs/snippets/package.json
Labels: area/documentation, type/dependencies, area/automation, size/XS

#1838 feat(parser): add types for built-in schemas
  packages/parser/src/envelopes/kafka.ts
  packages/parser/src/types/schema.ts
  packages/parser/tests/unit/envelopes/apigwt.test.ts
Labels: size/L, type/feature, type/tests, area/parser

#2197 chore(docs): add `ContextExamples` to upgrade guide
  docs/upgrade.md
Labels: area/documentation, size/M

#2178 chore(docs): fix typo in tracer.md
  docs/core/tracer.md
Labels: area/documentation, size/XS

#2192 feat(jmespath): add base types and errors
  packages/jmespath/src/Functions.ts
  packages/jmespath/src/constants.ts
  packages/jmespath/src/errors.ts
  packages/jmespath/src/types.ts
  packages/jmespath/typedoc.json
Labels: size/XL, type/feature, area/jmespath

#2200 chore(docs): remove missing README from typedoc for jmespath temporarily
  packages/jmespath/typedoc.json
Labels: size/XS

#2179 chore(parser): add parser subpath exports to package.json
  package-lock.json
  packages/parser/package.json
  packages/parser/src/envelopes/index.ts
  packages/parser/src/index.ts
  packages/parser/src/parser.ts
  packages/parser/src/schemas/index.ts
  packages/parser/src/types/ParserOptions.ts
  packages/parser/src/types/index.ts
  packages/parser/tests/unit/envelopes/apigwt.test.ts
  packages/parser/tests/unit/envelopes/apigwv2.test.ts
  packages/parser/tests/unit/envelopes/cloudwatch.test.ts
  packages/parser/tests/unit/envelopes/dynamodb.test.ts
  packages/parser/tests/unit/envelopes/eventbridge.test.ts
  packages/parser/tests/unit/envelopes/kafka.test.ts
  packages/parser/tests/unit/envelopes/kinesis-firehose.test.ts
  packages/parser/tests/unit/envelopes/kinesis.test.ts
  packages/parser/tests/unit/envelopes/lambda.test.ts
  packages/parser/tests/unit/envelopes/sns.test.ts
  packages/parser/tests/unit/envelopes/sqs.test.ts
  packages/parser/tests/unit/envelopes/vpc-lattice.test.ts
  packages/parser/tests/unit/envelopes/vpc-latticev2.test.ts
  packages/parser/tests/unit/parser.decorator.test.ts
  packages/parser/tests/unit/parser.middy.test.ts
  packages/parser/tests/unit/schema/alb.test.ts
  packages/parser/tests/unit/schema/apigw.test.ts
  packages/parser/tests/unit/schema/apigwv2.test.ts
  packages/parser/tests/unit/schema/cloudformation-custom-resource.test.ts
  packages/parser/tests/unit/schema/cloudwatch.test.ts
  packages/parser/tests/unit/schema/dynamodb.test.ts
  packages/parser/tests/unit/schema/eventbridge.test.ts
  packages/parser/tests/unit/schema/kafka.test.ts
  packages/parser/tests/unit/schema/kinesis.test.ts
  packages/parser/tests/unit/schema/lambda.test.ts
  packages/parser/tests/unit/schema/s3.test.ts
  packages/parser/tests/unit/schema/ses.test.ts
  packages/parser/tests/unit/schema/sns.test.ts
  packages/parser/tests/unit/schema/sqs.test.ts
  packages/parser/tests/unit/schema/vpc-lattice.test.ts
  packages/parser/tests/unit/schema/vpc-latticev2.test.ts
Labels: type/dependencies, size/L, type/tests, area/parser

#2194 feat(logger): improve regex in stack trace parsing
  packages/logger/src/formatter/LogFormatter.ts
  packages/logger/tests/unit/formatter/PowertoolsLogFormatter.test.ts
Labels: area/logger, size/L, type/feature, type/tests

#2226 docs(maintenance): update v1 and v2 status
  docs/overrides/main.html
  docs/upgrade.md
  docs/versioning.md
Labels: area/documentation, size/S

#2233 fix(idempotency): transform private class fields
  tsconfig.esm.json
Labels: type/bug, size/XS

#2232 fix(layers): add `createRequire` banner in esm
  layers/src/layer-publisher-stack.ts
Labels: type/bug, size/S, area/layers

#2212 feat(jmespath): add Expression and utils
  packages/jmespath/src/Expression.ts
  packages/jmespath/src/TreeInterpreter.ts
  packages/jmespath/src/utils.ts
Labels: size/L, type/feature

#2213 feat(jmespath): add abstract syntax tree definition
  packages/jmespath/src/ast.ts
Labels: size/L, type/feature

#2214 feat(jmespath): add lexer component
  packages/jmespath/src/Lexer.ts
Labels: size/L, type/feature

#2259 feat(jmespath): add built in functions
  packages/jmespath/src/Functions.ts
Labels: size/XL, type/feature

#2244 feat(parser): implement `safeParse` option
  packages/parser/src/envelopes/apigw.ts
  packages/parser/src/envelopes/apigwv2.ts
  packages/parser/src/envelopes/cloudwatch.ts
  packages/parser/src/envelopes/dynamodb.ts
  packages/parser/src/envelopes/envelope.ts
  packages/parser/src/envelopes/event-bridge.ts
  packages/parser/src/envelopes/index.ts
  packages/parser/src/envelopes/kafka.ts
  packages/parser/src/envelopes/kinesis-firehose.ts
  packages/parser/src/envelopes/kinesis.ts
  packages/parser/src/envelopes/lambda.ts
  packages/parser/src/envelopes/sns.ts
  packages/parser/src/envelopes/sqs.ts
  packages/parser/src/envelopes/vpc-lattice.ts
  packages/parser/src/envelopes/vpc-latticev2.ts
  packages/parser/src/index.ts
  packages/parser/src/middleware/parser.ts
  packages/parser/src/parser.ts
  packages/parser/src/parserDecorator.ts
  packages/parser/src/types/ParserOptions.ts
  packages/parser/src/types/envelope.ts
  packages/parser/src/types/index.ts
  packages/parser/src/types/parser.ts
  packages/parser/src/types/schema.ts
  packages/parser/tests/unit/envelope.test.ts
  packages/parser/tests/unit/envelopes/apigwt.test.ts
  packages/parser/tests/unit/envelopes/apigwv2.test.ts
  packages/parser/tests/unit/envelopes/cloudwatch.test.ts
  packages/parser/tests/unit/envelopes/dynamodb.test.ts
  packages/parser/tests/unit/envelopes/eventbridge.test.ts
  packages/parser/tests/unit/envelopes/kafka.test.ts
  packages/parser/tests/unit/envelopes/kinesis-firehose.test.ts
  packages/parser/tests/unit/envelopes/kinesis.test.ts
  packages/parser/tests/unit/envelopes/lambda.test.ts
  packages/parser/tests/unit/envelopes/sns.test.ts
  packages/parser/tests/unit/envelopes/sqs.test.ts
  packages/parser/tests/unit/envelopes/vpc-lattice.test.ts
  packages/parser/tests/unit/envelopes/vpc-latticev2.test.ts
  packages/parser/tests/unit/parser.decorator.test.ts
  packages/parser/tests/unit/parser.middy.test.ts
Labels: size/XXL, type/feature, type/tests, area/parser

#2264 feat(jmespath): add powertools functions
  packages/jmespath/src/PowertoolsFunctions.ts
Labels: size/M, type/feature

#2187 docs(jmespath): add utility docs
  docs/snippets/jmespath/extractDataFromBuiltinEnvelope.json
  docs/snippets/jmespath/extractDataFromBuiltinEnvelope.ts
  docs/snippets/jmespath/extractDataFromEnvelope.json
  docs/snippets/jmespath/extractDataFromEnvelope.ts
  docs/snippets/jmespath/powertoolsBase64GzipJmespath.ts
  docs/snippets/jmespath/powertoolsBase64GzipJmespathPayload.json
  docs/snippets/jmespath/powertoolsBase64Jmespath.ts
  docs/snippets/jmespath/powertoolsBase64JmespathPayload.json
  docs/snippets/jmespath/powertoolsCustomFunction.json
  docs/snippets/jmespath/powertoolsCustomFunction.ts
  docs/snippets/jmespath/powertoolsJsonIdempotencyJmespath.json
  docs/snippets/jmespath/powertoolsJsonIdempotencyJmespath.ts
  docs/snippets/tsconfig.json
  docs/utilities/jmespath.md
  mkdocs.yml
  packages/jmespath/README.md
  packages/jmespath/typedoc.json
Labels: area/documentation, size/XL

#2247 chore(deps): replace deprecated lib to alternative
  package-lock.json
  packages/idempotency/package.json
  packages/parameters/package.json
  packages/parameters/src/base/transformValue.ts
  packages/parameters/tests/e2e/appConfigProvider.class.test.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
  packages/parameters/tests/unit/SSMProvider.test.ts
  packages/parameters/tests/unit/getAppConfig.test.ts
Labels: type/dependencies, area/parameters, size/S, type/tests

#2283 refactor(logger): use template literal instead of node:util format
  packages/logger/src/Logger.ts
Labels: area/logger, size/XS, type/enhancement

#2265 feat(jmespath): add tree interpreter
  packages/jmespath/src/TreeInterpreter.ts
Labels: size/L, type/feature

#2266 feat(jmespath): add parser component
  packages/jmespath/src/ParsedResult.ts
  packages/jmespath/src/Parser.ts
  packages/jmespath/src/envelopes.ts
  packages/jmespath/src/search.ts
  packages/jmespath/typedoc.json
Labels: size/XXL, type/feature

#2277 fix(logger): buffer logs emitted during init
  packages/logger/src/Logger.ts
  packages/logger/tests/unit/Logger.test.ts
Labels: type/bug, area/logger, size/L, type/tests

#2271 test(jmespath): 100% coverage and spec compliance
  .github/actions/cached-node-modules/action.yml
  .github/workflows/reusable-run-linting-check-and-unit-tests.yml
  packages/jmespath/src/index.ts
  packages/jmespath/tests/unit/compliance/base.test.ts
  packages/jmespath/tests/unit/compliance/boolean.test.ts
  packages/jmespath/tests/unit/compliance/current.test.ts
  packages/jmespath/tests/unit/compliance/escape.test.ts
  packages/jmespath/tests/unit/compliance/filters.test.ts
  packages/jmespath/tests/unit/compliance/functions.test.ts
  packages/jmespath/tests/unit/compliance/identifiers.test.ts
  packages/jmespath/tests/unit/compliance/indices.test.ts
  packages/jmespath/tests/unit/compliance/literal.test.ts
  packages/jmespath/tests/unit/compliance/multiselect.test.ts
  packages/jmespath/tests/unit/compliance/pipe.test.ts
  packages/jmespath/tests/unit/compliance/slice.test.ts
  packages/jmespath/tests/unit/compliance/syntax.test.ts
  packages/jmespath/tests/unit/compliance/unicode.test.ts
  packages/jmespath/tests/unit/compliance/wildcard.test.ts
  packages/jmespath/tests/unit/index.test.ts
  packages/jmespath/typedoc.json
Labels: area/automation, size/XXL

#2285 chore(maintenance): adjust type exports in parameters & idempotency
  packages/idempotency/package.json
  packages/parameters/package.json
Labels: type/dependencies, size/S
