Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2024-12, with the labels that each got.

#3403 docs: fix link to parser sub page in the README
  README.md
Labels: documentation, size/XS

#3416 docs: add videos section in community
  docs/we_made_this.md
Labels: documentation, size/S

#3415 fix(parser): make SNS subject field nullish
  packages/parser/src/schemas/sns.ts
  packages/parser/tests/events/snsSqsEvent.json
Labels: bug, size/XS, tests, parser
