Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2024-02, with the labels that each got.

#2001 chore(ci): fix repo references
  .github/scripts/label_missing_acknowledgement_section.js
  .github/workflows/reusable_publish_docs.yml
Labels: area/automation, size/XS

#2006 chore(ci): add versioning workflow for pre-release
  .github/actions/create-pr/action.yml
  .github/actions/create-pr/create_pr_for_staged_changes.sh
  .github/workflows/make-version.yml
Labels: area/automation, size/L

#2028 chore(ci): refactor release workflow
  .github/workflows/make-release.yml
  .github/workflows/make-version.yml
  .github/workflows/publish_layer.yml
  .github/workflows/reusable_update_layer_arn_docs.yml
Labels: area/automation, size/L

#2043 chore(ci): pull up update_layer_arn_docs and scope contents permissions
  .github/workflows/make-release.yml
  .github/workflows/make-version.yml
  .github/workflows/publish_layer.yml
  .github/workflows/reusable_deploy_layer_stack.yml
  .github/workflows/reusable_update_layer_arn_docs.yml
Labels: area/automation, size/L

#2065 chore(deps-dev): bump socks & ip-address
  package-lock.json
Labels: type/dependencies, size/XS

#2072 chore(docs): include badges in readme
  .github/workflows/pr-run-linting-check-and-unit-tests.yml
  README.md
Labels: area/automation, size/XS

#2074 chore(tests): change timeout reporting in idempotency e2e tests
  packages/idempotency/tests/e2e/idempotentDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/idempotentDecorator.test.ts
  packages/idempotency/tests/e2e/makeHandlerIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeHandlerIdempotent.test.ts
  packages/testing/src/TestInvocationLogs.ts
Labels: size/M, type/tests

#2080 chore(tests): revert change timeout reporting in idempotency e2e tests
  packages/idempotency/tests/e2e/idempotentDecorator.test.FunctionCode.ts
  packages/idempotency/tests/e2e/idempotentDecorator.test.ts
  packages/idempotency/tests/e2e/makeHandlerIdempotent.test.FunctionCode.ts
  packages/idempotency/tests/e2e/makeHandlerIdempotent.test.ts
  packages/testing/src/TestInvocationLogs.ts
Labels: size/M, type/tests

#2059 feat(idempotency): return existing record in IdempotencyValidationError
  packages/idempotency/src/errors.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
Labels: do-not-merge, area/idempotency, size/M, type/feature, type/tests

#2091 chore(docs): fix broken upgrade guide link in banner
  docs/overrides/main.html
Labels: area/documentation, size/XS

#2093 chore(ci): fix make-version workflow on detached head
  .github/workflows/make-version.yml
Labels: area/automation, size/XS

#2095 fix(ci): create one layer artifact per region & merge
  .github/workflows/publish_layer.yml
  .github/workflows/reusable_deploy_layer_stack.yml
Labels: type/bug, area/automation, size/S

#2099 chore(maintenance): add core team to code owners
  .github/CODEOWNERS
Labels: type/internal, size/XS

#2107 chore(ci): revert add new version to version.ts file
  .github/workflows/make-version.yml
Labels: area/automation, size/XS

#2108 chore(commons): bump ua version
  packages/commons/src/version.ts
Labels: size/XS, area/commons

#2110 chore(ci): fix release workflow permission
  .github/workflows/publish_layer.yml
Labels: area/automation, size/XS

#2131 chore(maintenance): migrate init script and husky to v9
  .husky/pre-commit
  .husky/pre-push
  package.json
Labels: type/dependencies, type/internal, size/XS
