Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2024-01, with the labels that each got.

#1834 docs: fix typos
  docs/maintainers.md
  docs/roadmap.md
  docs/snippets/batch/gettingStartedErrorHandling.ts
  docs/utilities/idempotency.md
Labels: area/documentation, type/internal, size/XS

#1779 feat(idempotency): leverage new dynamodB Failed conditional writes behavior
  docs/utilities/idempotency.md
  packages/idempotency/src/IdempotencyHandler.ts
  packages/idempotency/src/errors.ts
  packages/idempotency/src/persistence/BasePersistenceLayer.ts
  packages/idempotency/src/persistence/DynamoDBPersistenceLayer.ts
  packages/idempotency/tests/unit/IdempotencyHandler.test.ts
  packages/idempotency/tests/unit/persistence/BasePersistenceLayer.test.ts
  packages/idempotency/tests/unit/persistence/DynamoDbPersistenceLayer.test.ts
Labels: area/documentation, area/idempotency, size/L, type/feature, type/tests

#1860 chore(ci): allow dependabot PRs
  .github/semantic.yml
Labels: area/automation, size/XS

#1861 chore(ci): allow deps-dev for semantic PR
  .github/semantic.yml
Labels: area/automation, size/XS

#1862 chore(ci): Dependabot fine tuning
  .github/dependabot.yml
  .github/workflows/codeql.yml
  package-lock.json
Labels: type/dependencies, area/automation, size/M

#1916 fix(parameters): refresh AppConfig session token after 24 hrs
  packages/parameters/src/appconfig/AppConfigProvider.ts
  packages/parameters/src/constants.ts
  packages/parameters/tests/unit/AppConfigProvider.test.ts
Labels: type/bug, area/parameters, size/L, type/tests

#1917 chore(deps): fix dependencies and dependabot config
  .github/dependabot.yml
  docs/snippets/package.json
  examples/cdk/package.json
  examples/sam/package.json
  layers/package.json
  package-lock.json
  package.json
  packages/idempotency/package.json
  packages/logger/package.json
  packages/metrics/package.json
  packages/parameters/package.json
  packages/parameters/src/dynamodb/DynamoDBProvider.ts
  packages/testing/package.json
  packages/tracer/package.json
Labels: area/documentation, type/dependencies, area/parameters, size/L

#1924 chore(maintenance): fix install command for .devcontainer setup
  .devcontainer/Dockerfile
Labels: type/internal, size/XS

#1935 chore(maintenance): fine tune dependabot config
  .github/dependabot.yml
Labels: size/XS

#1957 chore(maintenance): add environment scope to npm token
  .github/workflows/make-release.yml
  .github/workflows/make-v2-release.yml
Labels: area/automation, size/XS

#1960 chore(docs): add link to performance tuning demo
  README.md
  docs/index.md
  packages/commons/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/tracer/README.md
Labels: area/documentation, type/internal, size/M

#1968 chore(maintenance): group CDK cli with other CDK dependencies
  .github/dependabot.yml
Labels: size/XS

#1970 chore(maintenance): add overwrite to artifact arn in layer pipeline
  .github/workflows/reusable_deploy_layer_stack.yml
Labels: area/automation, size/XS

#1979 chore(ci): refactor more workflows to scope permissions
  .github/workflows/make-v2-release.yml
  .github/workflows/on_doc_merge.yml
  .github/workflows/publish_layer.yml
  .github/workflows/rebuild_latest_docs.yml
  .github/workflows/reusable_publish_docs.yml
Labels: area/automation, size/S

#1996 docs(maintenance): add versioning and maintenance policy
  docs/versioning.md
  mkdocs.yml
Labels: area/documentation, size/L

#2000 chore(ci): fix docs workflow permissions
  .github/workflows/on_doc_merge.yml
  .github/workflows/rebuild_latest_docs.yml
Labels: area/automation, size/XS
