Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2025-04, with the labels that each got.

#3729 feat(parser): add Cognito pre-signup trigger schema
  docs/utilities/parser.md
  packages/parser/src/schemas/cognito.ts
  packages/parser/src/schemas/index.ts
  packages/parser/tests/events/cognito/base.json
  packages/parser/tests/unit/schema/cognito.test.ts
Labels: documentation, dependencies, size/XXL, tests, parser

#3807 feat(parser): add schema support for API Gateway WebSocket events
  docs/utilities/parser.md
  packages/parser/src/schemas/api-gateway-websocket.ts
  packages/parser/src/schemas/index.ts
  packages/parser/src/types/schema.ts
  packages/parser/tests/events/apigw-websocket/connectEvent.json
  packages/parser/tests/unit/schema/apigw-websocket.test.ts
Labels: documentation, size/L, feature, tests, parser

#3808 docs(parameters): clarify caching behavior of `getAppConfig`
  docs/index.md
  docs/utilities/parameters.md
  packages/idempotency/src/types/IdempotencyRecord.ts
Labels: documentation, idempotency, size/XS

#3818 docs: add getting started section
  docs/contributing/conventions.md
  docs/environment-variables.md
  docs/features/batch.md
  docs/features/event-handler/api-gateway.md
  docs/features/idempotency.md
  docs/features/index.md
  docs/features/jmespath.md
  docs/features/logger.md
  docs/features/metrics.md
  docs/features/parameters.md
  docs/features/parser.md
  docs/features/tracer.md
  docs/features/validation.md
  docs/getting-started/installation.md
  docs/getting-started/lambda-layers.md
  docs/getting-started/typescript-settings.md
  docs/getting-started/usage-patterns.md
  docs/index.md
  docs/upgrade.md
  examples/snippets/getting-started/patterns-decorator.ts
  examples/snippets/getting-started/patterns-functional.ts
  examples/snippets/getting-started/patterns-middyjs.ts
  mkdocs.yml
Labels: documentation, size/XXL

#3836 docs: fix copy-me button
  docs/getting-started/installation.md
  docs/getting-started/lambda-layers.md
  docs/stylesheets/extra.css
Labels: documentation, size/M

#3834 fix(logger): warn customers when the ALC log level is less verbose than log buffer
  packages/logger/src/Logger.ts
  packages/logger/tests/unit/logBuffer.test.ts
Labels: bug, logger, size/M, tests

#3848 docs: Update metrics docs to mention correct POWERTOOLS_METRICS_DISABLED variable name.
  docs/environment-variables.md
  docs/features/metrics.md
  examples/snippets/metrics/testingMetrics.ts
Labels: documentation, size/S

#3854 chore: update cdk output dir
  packages/testing/src/TestStack.ts
Labels: size/XS

#3855 fix(parser): Make Kafka key property optional
  packages/parser/src/schemas/kafka.ts
Labels: bug, size/XS, parser

#3858 feat(event-handler): AppSync Events resolver
  docs/features/event-handler/appsync-events.md
  docs/features/index.md
  docs/index.md
  examples/snippets/event-handler/appsync-events/accessEventAndContext.ts
  examples/snippets/event-handler/appsync-events/aggregatedProcessing.ts
  examples/snippets/event-handler/appsync-events/allOrNothingBatch.ts
  examples/snippets/event-handler/appsync-events/debugLogging.ts
  examples/snippets/event-handler/appsync-events/errorHandlingWithBatchOfItems.ts
  examples/snippets/event-handler/appsync-events/errorHandlingWithIndividualItems.ts
  examples/snippets/event-handler/appsync-events/gettingStartedOnPublish.ts
  examples/snippets/event-handler/appsync-events/gettingStartedOnPublishDecorator.ts
  examples/snippets/event-handler/appsync-events/gettingStartedOnSubscribe.ts
  examples/snippets/event-handler/appsync-events/gettingStartedOnSubscribeDecorator.ts
  examples/snippets/event-handler/appsync-events/samples/allOrNothingErrorResponse.json
  examples/snippets/event-handler/appsync-events/samples/debugLogExcerpt.json
  examples/snippets/event-handler/appsync-events/samples/errorHandlingWithAggregateResponse.json
  examples/snippets/event-handler/appsync-events/samples/errorHandlingWithIndividualItemsResponse.json
  examples/snippets/event-handler/appsync-events/samples/gettingStartedRequest.json
  examples/snippets/event-handler/appsync-events/samples/gettingStartedResponse.json
  examples/snippets/event-handler/appsync-events/samples/gettingStartedResponseWithError.json
  examples/snippets/event-handler/appsync-events/samples/onPublishEvent.json
  examples/snippets/event-handler/appsync-events/samples/onSubscribeEvent.json
  examples/snippets/event-handler/appsync-events/templates/gettingStarted.yaml
  examples/snippets/event-handler/appsync-events/testingEventsOnPublish.ts
  examples/snippets/event-handler/appsync-events/testingEventsOnSubscribe.ts
  examples/snippets/event-handler/appsync-events/unauthorizedException.ts
  examples/snippets/event-handler/appsync-events/wildcardPatterns.ts
  mkdocs.yml
  packages/event-handler/README.md
  packages/event-handler/package.json
  packages/event-handler/src/appsync-events/AppSyncEventsResolver.ts
  packages/event-handler/src/appsync-events/RouteHandlerRegistry.ts
  packages/event-handler/src/appsync-events/Router.ts
  packages/event-handler/src/appsync-events/errors.ts
  packages/event-handler/src/appsync-events/index.ts
  packages/event-handler/src/appsync-events/utils.ts
  packages/event-handler/src/index.ts
  packages/event-handler/src/types/appsync-events.ts
  packages/event-handler/src/types/index.ts
  packages/event-handler/tests/events/onPublish.json
  packages/event-handler/tests/helpers/factories.ts
  packages/event-handler/tests/unit/AppSyncEventsResolver.test.ts
  packages/event-handler/tests/unit/RouteHandlerRegistry.test.ts
  packages/event-handler/tests/unit/Router.test.ts
  packages/event-handler/tests/unit/index.test.ts
  packages/event-handler/typedoc.json
  typedoc.json
Labels: documentation, dependencies, internal, size/XXL, feature

#3852 improv(logger): Format the stack trace as an array of strings in dev mode
  packages/logger/src/formatter/LogFormatter.ts
  packages/logger/tests/unit/initializeLogger.test.ts
  packages/logger/tests/unit/workingWithkeys.test.ts
Labels: logger, size/M, tests, enhancement

#3864 chore: update snippets & event-handler docs
  .github/scripts/release_patch_package_json.js
  docs/environment-variables.md
  docs/features/event-handler/appsync-events.md
  docs/getting-started/lambda-layers.md
  examples/snippets/event-handler/appsync-events/accessEventAndContext.ts
  examples/snippets/event-handler/appsync-events/debugLogging.ts
  examples/snippets/event-handler/appsync-events/templates/gettingStarted.yaml
  examples/snippets/package.json
  package-lock.json
Labels: documentation, dependencies, automation, size/L

#3869 chore: add customer reference
  README.md
  docs/index.md
  docs/media/logos/ours_privacy.svg
  packages/batch/README.md
  packages/commons/README.md
  packages/event-handler/README.md
  packages/idempotency/README.md
  packages/jmespath/README.md
  packages/logger/README.md
  packages/metrics/README.md
  packages/parameters/README.md
  packages/parser/README.md
  packages/tracer/README.md
  packages/validation/README.md
Labels: documentation, internal, size/S

#3872 chore: restore typeVersions for old ts config
  packages/event-handler/package.json
  packages/parser/package.json
  packages/validation/package.json
Labels: dependencies, size/M
