Repository aws-powertools/powertools-lambda-typescript, pull requests merged in 2025-06, with the labels that each got.

#3982 fix(parameters): preserve original stack trace on transform failures …
  packages/parameters/src/base/BaseProvider.ts
  packages/parameters/tests/unit/BaseProvider.test.ts
Labels: bug, parameters, size/M, tests

#3991 docs(event-handler): add docs page for Bedrock Agent Function
  docs/features/event-handler/bedrock-agents.md
  examples/snippets/event-handler/bedrock-agents/accessEventAndContext.ts
  examples/snippets/event-handler/bedrock-agents/debugLogging.ts
  examples/snippets/event-handler/bedrock-agents/gettingStartedFunctionsTool.ts
  examples/snippets/event-handler/bedrock-agents/sessionAttributes.ts
  examples/snippets/event-handler/bedrock-agents/stopConversation.ts
  examples/snippets/event-handler/bedrock-agents/templates/gettingStartedCdk.ts
  examples/snippets/event-handler/bedrock-agents/templates/gettingStartedSam.yaml
  mkdocs.yml
  packages/event-handler/README.md
  packages/event-handler/src/types/bedrock-agent.ts
Labels: documentation, internal, size/XL, event-handler

#4010 docs: add bedrock agents page to llmtxt
  mkdocs.yml
Labels: documentation, size/XS

#4063 chore: add kafka scope to semantic config
  .github/semantic.yml
Labels: automation, size/XS

#4076 docs(kafka): finalize Kafka docs
  docs/features/kafka.md
  examples/snippets/kafka/advancedBasicErrorHandling.ts
  examples/snippets/kafka/advancedHandlingLargeMessages.ts
  examples/snippets/kafka/advancedParserErrorHandling.ts
  examples/snippets/kafka/advancedTestingYourCode.ts
  examples/snippets/kafka/advancedWorkingWithArkType.ts
  examples/snippets/kafka/advancedWorkingWithRecordMetadata.ts
  examples/snippets/kafka/advancedWorkingWithValibot.ts
  examples/snippets/kafka/advancedWorkingWithZod.ts
  examples/snippets/kafka/gettingStartedPrimitiveValues.ts
  examples/snippets/kafka/templates/advancedBatchSizeConfiguration.yaml
  packages/kafka/README.md
  packages/kafka/src/consumer.ts
  packages/kafka/src/errors.ts
  packages/kafka/tests/unit/consumer.test.ts
Labels: documentation, size/XL

#4094 docs(kafka): provide example payloads
  docs/features/kafka.md
  examples/snippets/kafka/advancedWorkingWithIdempotency.ts
  examples/snippets/kafka/advancedWorkingWithRecordMetadata.ts
  examples/snippets/kafka/gettingStartedPrimitiveValues.ts
  examples/snippets/kafka/gettingStartedProtobuf.ts
  examples/snippets/kafka/gettingStartedValueOnly.ts
  examples/snippets/kafka/samples/kafkaEventAvro.json
  examples/snippets/kafka/samples/kafkaEventJson.json
  examples/snippets/kafka/samples/kafkaEventProtobuf.json
  examples/snippets/kafka/samples/user.avsc
  examples/snippets/kafka/samples/user.es6.generated.d.ts
  examples/snippets/kafka/samples/user.es6.generated.js
  examples/snippets/kafka/samples/user.generated.d.ts
  examples/snippets/kafka/samples/user.generated.js
  examples/snippets/kafka/samples/user.json
  examples/snippets/kafka/samples/user.proto
  examples/snippets/kafka/templates/advancedBatchSizeConfiguration.yaml
  examples/snippets/kafka/templates/gettingStartedWithMsk.yaml
  packages/kafka/package.json
Labels: documentation, dependencies, size/XL

#4096 docs: update layers version + simplify script
  .github/scripts/update_layer_arn.sh
  .github/workflows/make-release.yml
  .github/workflows/publish_layer.yml
  docs/getting-started/lambda-layers.md
  examples/app/cdk/example-stack.ts
  examples/app/template.yaml
Labels: documentation, automation, size/L

#3999 feat(event-handler): add single resolver functionality for AppSync GraphQL API
  packages/event-handler/src/appsync-graphql/AppSyncGraphQLResolver.ts
  packages/event-handler/src/appsync-graphql/RouteHandlerRegistry.ts
  packages/event-handler/src/appsync-graphql/Router.ts
  packages/event-handler/src/appsync-graphql/errors.ts
  packages/event-handler/src/appsync-graphql/scalarTypesUtils.ts
  packages/event-handler/src/appsync-graphql/utils.ts
  packages/event-handler/src/types/appsync-graphql.ts
  packages/event-handler/tests/helpers/factories.ts
  packages/event-handler/tests/unit/appsync-graphql/AppSyncGraphQLResolver.test.ts
  packages/event-handler/tests/unit/appsync-graphql/RouteHandlerRegistry.test.ts
  packages/event-handler/tests/unit/appsync-graphql/Router.test.ts
  packages/event-handler/tests/unit/appsync-graphql/scalarTypesUtils.test.ts
Labels: size/XXL, tests, event-handler
